//! 802.11 association FSM + 4-way handshake (Phase 81, Task B.5).
//!
//! The FSM models the STA (station) side of WPA2-PSK association:
//! Init → Scanning → Authenticating → Associating → Handshake → Connected.
//!
//! Handshake sub-steps:
//!   WaitM1 — waiting for EAPOL M1 (AP ANonce)
//!   WaitM3 — waiting for EAPOL M3 (AP verifies M2 MIC, delivers encrypted GTK)
//!   Done   — M4 sent, keys installed, transition to Connected
//!
//! The FSM produces a sequence of `WifiAction` values for each `WifiEvent` it
//! processes; callers dispatch actions (send frames, install keys, etc.).

use crate::control::WifiStatus;
use crate::eapol::{EapolKeyFrame, KEY_INFO_M2, KEY_INFO_M4, KeyInfo, MIC_OFFSET, mic_sha1_128};
use crate::kdf::{Ptk, derive_ptk};
use crate::mgmt::{BssInfo, RsnIe, build_assoc_request, build_auth_open};
use alloc::vec;
use alloc::vec::Vec;

// ── CIPHER constant ───────────────────────────────────────────────────────────

/// CCMP-128 pairwise-cipher discriminator stored in [`KeyMaterial`].
///
/// This is a **software-internal tag** consumed only by host code to label the
/// key material; it is deliberately NOT the on-wire MCU cipher selector. The
/// value posted to silicon is `kernel_core::mt792x::mcu::CIPHER_CCMP`
/// (`MCU_CIPHER_AES_CCMP = 5`), which the driver's key-install path uses. The
/// two are intentionally independent: changing this tag does not change what is
/// sent to the chip.
pub const CIPHER_CCMP: u8 = 0x01;

// ── Public types ─────────────────────────────────────────────────────────────

/// Current state of the Wi-Fi FSM.
#[derive(Debug, Clone, PartialEq)]
pub enum WifiState {
    /// Initial state — no scan initiated.
    Init,
    /// Scanning for the target SSID.
    Scanning,
    /// Open-system authentication frame sent; awaiting auth-resp.
    Authenticating,
    /// Association request sent; awaiting assoc-resp.
    Associating,
    /// 4-way EAPOL handshake in progress.
    Handshake(HandshakeStep),
    /// Connected and keys installed.
    Connected,
    /// Terminal failure state.
    Failed(FailReason),
}

/// EAPOL 4-way handshake sub-state.
#[derive(Debug, Clone, PartialEq)]
pub enum HandshakeStep {
    /// Waiting for M1 (ANonce from AP).
    WaitM1,
    /// M2 sent; waiting for M3 (GTK + MIC from AP).
    WaitM3,
    /// M4 sent; transition to Connected is next.
    Done,
}

/// Reason for entering `WifiState::Failed`.
#[derive(Debug, Clone, PartialEq)]
pub enum FailReason {
    /// AP rejected association with a non-success status code.
    BadRsnParams,
    /// 4-way handshake did not complete before timeout.
    HandshakeTimeout,
    /// AP or peer sent a Deauth while associated.
    Deauthed,
    /// AP rejected authentication (auth-resp status != 0).
    AuthRejected,
    /// AP rejected association (assoc-resp status != 0).
    AssocRejected,
}

/// Key material produced after a successful 4-way handshake.
#[derive(Debug, Clone)]
pub struct KeyMaterial {
    /// Temporal Key (TK) for unicast encryption.
    pub tk: [u8; 16],
    /// Group Temporal Key (GTK) bytes.
    pub gtk: Vec<u8>,
    /// GTK index (0–3).
    pub gtk_idx: u8,
    /// Pairwise cipher (CIPHER_CCMP = 0x01).
    pub pairwise_cipher: u8,
}

/// Events delivered to the FSM from the driver / timer.
#[derive(Debug)]
pub enum WifiEvent {
    /// A BSS was found during a scan.
    ProbeResp(BssInfo),
    /// Authentication response received from AP.
    AuthResp { status: u16 },
    /// Association response received from AP.
    AssocResp { status: u16 },
    /// Raw EAPOL frame received.
    Eapol(Vec<u8>),
    /// A timeout fired (used for handshake timeout).
    Timeout,
    /// Deauthentication received.
    Deauth,
}

/// Actions returned by the FSM to its caller.
#[derive(Debug)]
pub enum WifiAction {
    /// Transmit a management or EAPOL frame.
    SendMgmt(Vec<u8>),
    /// Transmit an EAPOL frame.
    SendEapol(Vec<u8>),
    /// Install session keys into the driver.
    InstallKey(KeyMaterial),
    /// Purge all session keys from the driver.
    PurgeKeys,
    /// Emit a status update (e.g. to `m3ctl` / `wpa_monitor`).
    Emit(WifiStatus),
}

// ── FSM ───────────────────────────────────────────────────────────────────────

/// Wi-Fi association FSM.
pub struct WifiFsm {
    /// PMK (derived from passphrase at config parse time).
    pmk: [u8; 32],
    /// Target SSID.
    ssid: Vec<u8>,
    /// Our (STA) MAC address.
    spa: [u8; 6],
    /// AP (BSSID) MAC address (filled once we pick a BSS).
    bssid: Option<[u8; 6]>,
    /// ANonce received from AP in M1.
    anonce: Option<[u8; 32]>,
    /// SNonce generated by us for M2.
    snonce: Option<[u8; 32]>,
    /// Replay counter from last seen M1/M3 (must be monotonically increasing).
    last_replay_counter: u64,
    /// PTK derived after receiving M1.
    ptk: Option<Ptk>,
    /// Current FSM state.
    state: WifiState,
    /// SNonce injected by the driver (from kernel `getrandom` entropy) or by
    /// tests. When `Some`, `generate_snonce` returns it instead of the
    /// deterministic fallback — this is the production handshake path.
    snonce_override: Option<[u8; 32]>,
}

impl WifiFsm {
    /// Create a new FSM in the `Init` state.
    ///
    /// `pmk`  — 32-byte WPA2 PMK (from `crypto_lib::hash::wpa_pmk`).
    /// `ssid` — target SSID bytes.
    /// `spa`  — STA (our) MAC address.
    pub fn new(pmk: [u8; 32], ssid: Vec<u8>, spa: [u8; 6]) -> Self {
        Self {
            pmk,
            ssid,
            spa,
            bssid: None,
            anonce: None,
            snonce: None,
            last_replay_counter: 0,
            ptk: None,
            state: WifiState::Init,
            snonce_override: None,
        }
    }

    /// Create a new FSM with a caller-supplied SNonce.
    ///
    /// The production driver passes a fresh 32-byte SNonce drawn from the kernel
    /// CSPRNG (`getrandom`) so the 4-way handshake nonce is unpredictable; tests
    /// pass a fixed vector for determinism.
    pub fn new_with_snonce(pmk: [u8; 32], ssid: Vec<u8>, spa: [u8; 6], snonce: [u8; 32]) -> Self {
        let mut fsm = Self::new(pmk, ssid, spa);
        fsm.snonce_override = Some(snonce);
        fsm
    }

    /// Current FSM state.
    pub fn state(&self) -> &WifiState {
        &self.state
    }

    /// Process a `WifiEvent` and return the resulting actions.
    pub fn on_event(&mut self, ev: WifiEvent) -> Vec<WifiAction> {
        match ev {
            WifiEvent::ProbeResp(bss) => self.handle_probe_resp(bss),
            WifiEvent::AuthResp { status } => self.handle_auth_resp(status),
            WifiEvent::AssocResp { status } => self.handle_assoc_resp(status),
            WifiEvent::Eapol(frame) => self.handle_eapol(frame),
            WifiEvent::Timeout => self.handle_timeout(),
            WifiEvent::Deauth => self.handle_deauth(),
        }
    }

    // ── Event handlers ────────────────────────────────────────────────────────

    fn handle_probe_resp(&mut self, bss: BssInfo) -> Vec<WifiAction> {
        if !matches!(self.state, WifiState::Scanning) {
            return vec![];
        }
        // Only accept BSS matching our target SSID with CCMP+PSK RSN support.
        if bss.ssid != self.ssid || !bss.rsn {
            return vec![];
        }
        self.bssid = Some(bss.bssid);
        self.state = WifiState::Authenticating;
        // Send Open System auth frame.
        let auth_frame = build_auth_open(1);
        vec![WifiAction::SendMgmt(auth_frame)]
    }

    fn handle_auth_resp(&mut self, status: u16) -> Vec<WifiAction> {
        if !matches!(self.state, WifiState::Authenticating) {
            return vec![];
        }
        if status != 0 {
            self.state = WifiState::Failed(FailReason::AuthRejected);
            return vec![WifiAction::Emit(self.disconnected_status())];
        }
        self.state = WifiState::Associating;
        let rsn_ie = RsnIe::ccmp_psk().encode();
        let rates: &[u8] = &[0x82, 0x84, 0x8B, 0x96, 0x0C, 0x12, 0x18, 0x24];
        let assoc_frame = build_assoc_request(&self.ssid, &rsn_ie, rates);
        vec![WifiAction::SendMgmt(assoc_frame)]
    }

    fn handle_assoc_resp(&mut self, status: u16) -> Vec<WifiAction> {
        if !matches!(self.state, WifiState::Associating) {
            return vec![];
        }
        if status != 0 {
            // Status codes 43/45 indicate RSN/cipher mismatch.
            self.state = WifiState::Failed(FailReason::BadRsnParams);
            return vec![WifiAction::Emit(self.disconnected_status())];
        }
        self.state = WifiState::Handshake(HandshakeStep::WaitM1);
        vec![]
    }

    fn handle_eapol(&mut self, raw: Vec<u8>) -> Vec<WifiAction> {
        let frame = match EapolKeyFrame::parse(&raw) {
            Some(f) => f,
            None => return vec![],
        };

        match &self.state.clone() {
            WifiState::Handshake(HandshakeStep::WaitM1) => self.handle_m1(frame),
            // M3 verifies the MIC over the EXACT received bytes (see handle_m3),
            // so the raw buffer is threaded through alongside the parsed frame.
            WifiState::Handshake(HandshakeStep::WaitM3) => self.handle_m3(&raw, frame),
            _ => vec![],
        }
    }

    fn handle_m1(&mut self, frame: EapolKeyFrame) -> Vec<WifiAction> {
        // M1: ACK set, MIC clear, Pairwise set.
        if !frame.key_info.key_ack() || frame.key_info.key_mic() || !frame.key_info.pairwise() {
            return vec![]; // not a valid M1
        }

        let replay_counter = frame.replay_counter;
        // Replay counter check: M1 replay counter must be > last seen.
        if replay_counter <= self.last_replay_counter && self.last_replay_counter != 0 {
            return vec![]; // stale replay counter — drop
        }
        self.last_replay_counter = replay_counter;

        let mut anonce = [0u8; 32];
        anonce.copy_from_slice(&frame.nonce);
        self.anonce = Some(anonce);

        // Generate (or use injected) SNonce.
        let snonce = self.generate_snonce();
        self.snonce = Some(snonce);

        // Derive PTK.
        let bssid = match self.bssid {
            Some(b) => b,
            None => return vec![],
        };
        let ptk = derive_ptk(&self.pmk, &bssid, &self.spa, &anonce, &snonce);
        self.ptk = Some(ptk.clone());

        // Build M2.
        let m2 = self.build_m2(replay_counter, &snonce, &ptk);
        self.state = WifiState::Handshake(HandshakeStep::WaitM3);
        vec![WifiAction::SendEapol(m2)]
    }

    fn handle_m3(&mut self, raw: &[u8], frame: EapolKeyFrame) -> Vec<WifiAction> {
        // M3: ACK + MIC + Install + Secure + Encrypted set.
        if !frame.key_info.key_ack()
            || !frame.key_info.key_mic()
            || !frame.key_info.install()
            || !frame.key_info.secure()
        {
            return vec![]; // not a valid M3 shape
        }

        let replay_counter = frame.replay_counter;
        // Replay counter must be strictly greater than M1's.
        if replay_counter <= self.last_replay_counter {
            return vec![]; // stale or replayed — drop
        }

        let ptk = match &self.ptk {
            Some(p) => p.clone(),
            None => return vec![],
        };

        // Verify the M3 MIC over the EXACT received bytes, with only the 16 MIC
        // bytes zeroed in place (IEEE 802.11i). Verifying over `frame.encode()`
        // would silently depend on encode() round-tripping every field
        // (e.g. the reserved Key-ID octets) and could accept or reject a frame
        // for the wrong reason; HMACing the original bytes avoids that.
        if raw.len() < MIC_OFFSET + 16 {
            return vec![]; // too short to carry a MIC
        }
        let mut frame_bytes = raw.to_vec();
        frame_bytes[MIC_OFFSET..MIC_OFFSET + 16].fill(0);
        let computed_mic = mic_sha1_128(&ptk.kck, &frame_bytes);
        // Zero local copy
        frame_bytes.fill(0);

        if computed_mic != frame.mic {
            // Bad MIC — drop, do NOT install keys.
            return vec![];
        }

        self.last_replay_counter = replay_counter;

        // Unwrap GTK from key-data.
        let gtk_result = crate::kdf::unwrap_gtk(&ptk.kek, &frame.key_data);
        let gtk = match gtk_result {
            Ok(g) => g,
            Err(_) => return vec![], // key-data decode error
        };

        // Build and send M4.
        let m4 = self.build_m4(replay_counter, &ptk);
        self.state = WifiState::Handshake(HandshakeStep::Done);

        let key_material = KeyMaterial {
            tk: ptk.tk,
            gtk: gtk.bytes,
            gtk_idx: gtk.key_idx,
            pairwise_cipher: CIPHER_CCMP,
        };

        self.state = WifiState::Connected;
        vec![
            WifiAction::SendEapol(m4),
            WifiAction::InstallKey(key_material),
            WifiAction::Emit(self.connected_status()),
        ]
    }

    fn handle_timeout(&mut self) -> Vec<WifiAction> {
        // Only handle timeout in Handshake states.
        if !matches!(self.state, WifiState::Handshake(_)) {
            return vec![];
        }
        // Send a Deauth to the AP and enter Failed state.
        let deauth = build_auth_open(3); // seq=3 is a conventional deauth signal
        self.state = WifiState::Failed(FailReason::HandshakeTimeout);
        vec![
            WifiAction::SendMgmt(deauth),
            WifiAction::Emit(self.disconnected_status()),
        ]
    }

    fn handle_deauth(&mut self) -> Vec<WifiAction> {
        // Deauth while connected or in handshake.
        if matches!(self.state, WifiState::Init | WifiState::Failed(_)) {
            return vec![];
        }
        self.state = WifiState::Failed(FailReason::Deauthed);
        vec![
            WifiAction::PurgeKeys,
            WifiAction::Emit(self.disconnected_status()),
        ]
    }

    // ── Builders ──────────────────────────────────────────────────────────────

    fn build_m2(&self, replay_counter: u64, snonce: &[u8; 32], ptk: &Ptk) -> Vec<u8> {
        let rsn_ie = RsnIe::ccmp_psk().encode();
        let mut frame = EapolKeyFrame {
            version: 1,
            desc_type: 2,
            key_info: KeyInfo(KEY_INFO_M2),
            key_length: 16,
            replay_counter,
            nonce: *snonce,
            iv: [0u8; 16],
            rsc: [0u8; 8],
            mic: [0u8; 16], // zeroed for MIC computation
            key_data: rsn_ie,
        };
        let encoded = frame.encode();
        let mic = mic_sha1_128(&ptk.kck, &encoded);
        frame.mic = mic;
        frame.encode()
    }

    fn build_m4(&self, replay_counter: u64, ptk: &Ptk) -> Vec<u8> {
        let mut frame = EapolKeyFrame {
            version: 1,
            desc_type: 2,
            key_info: KeyInfo(KEY_INFO_M4),
            key_length: 0,
            replay_counter,
            nonce: [0u8; 32],
            iv: [0u8; 16],
            rsc: [0u8; 8],
            mic: [0u8; 16],
            key_data: Vec::new(),
        };
        let encoded = frame.encode();
        let mic = mic_sha1_128(&ptk.kck, &encoded);
        frame.mic = mic;
        frame.encode()
    }

    // ── SNonce generation ─────────────────────────────────────────────────────

    fn generate_snonce(&self) -> [u8; 32] {
        // Production path: the driver injects a fresh SNonce from kernel entropy
        // via `new_with_snonce`, so `snonce_override` is always `Some` for a real
        // association. This is the only secure path.
        if let Some(s) = self.snonce_override {
            return s;
        }
        // Deterministic fallback for the entropy-less `new` constructor (used by
        // passive/non-associating contexts and as a `no_std` safety net). This
        // is NOT used by the driver, which always uses `new_with_snonce`.
        let mut rng = crypto_lib::random::CsprngState::from_seed([0xA5u8; 32]);
        let mut snonce = [0u8; 32];
        crypto_lib::random::csprng_fill(&mut rng, &mut snonce);
        snonce
    }

    // ── Status helpers ────────────────────────────────────────────────────────

    fn connected_status(&self) -> WifiStatus {
        WifiStatus {
            ssid: self.ssid.clone(),
            rssi: 0,
            ipv4: [0, 0, 0, 0],
        }
    }

    fn disconnected_status(&self) -> WifiStatus {
        WifiStatus {
            ssid: Vec::new(),
            rssi: 0,
            ipv4: [0, 0, 0, 0],
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::eapol::{KEY_INFO_M1, KEY_INFO_M3};
    use crate::kdf::{derive_ptk, tests::ptk_vector_inputs};

    /// Shared PMK for FSM tests.
    fn test_pmk() -> [u8; 32] {
        let (pmk, ..) = ptk_vector_inputs();
        pmk
    }

    /// Shared SNonce for deterministic tests.
    fn test_snonce() -> [u8; 32] {
        [0x22u8; 32]
    }

    /// Shared ANonce.
    fn test_anonce() -> [u8; 32] {
        [0x11u8; 32]
    }

    /// AP BSSID.
    fn ap_bssid() -> [u8; 6] {
        [0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0x01]
    }

    /// STA MAC.
    fn sta_mac() -> [u8; 6] {
        [0x00, 0x11, 0x22, 0x33, 0x44, 0x55]
    }

    /// Build a synthetic EAPOL M1 frame.
    fn make_m1(anonce: &[u8; 32], replay_counter: u64) -> Vec<u8> {
        EapolKeyFrame {
            version: 1,
            desc_type: 2,
            key_info: KeyInfo(KEY_INFO_M1),
            key_length: 16,
            replay_counter,
            nonce: *anonce,
            iv: [0u8; 16],
            rsc: [0u8; 8],
            mic: [0u8; 16],
            key_data: Vec::new(),
        }
        .encode()
    }

    /// Build a synthetic EAPOL M3 frame with a correct MIC and wrapped GTK.
    fn make_m3(
        anonce: &[u8; 32],
        snonce: &[u8; 32],
        replay_counter: u64,
        tamper_mic: bool,
    ) -> Vec<u8> {
        let (pmk, ..) = ptk_vector_inputs();
        let aa = ap_bssid();
        let spa = sta_mac();
        let ptk = derive_ptk(&pmk, &aa, &spa, anonce, snonce);

        // Build standards-shaped M3 key-data: AES-Key-Wrap of a real GTK KDE
        // ([0xDD][len][00 0F AC][01][KeyInfo][rsv][GTK]), exactly what a real AP
        // sends and what `unwrap_gtk` now parses.
        let gtk_plain = [0x42u8; 16]; // synthetic GTK plaintext
        let kde = crate::kdf::build_gtk_kde(&gtk_plain, 0); // key_idx = 0
        let key_data = crypto_lib::symmetric::aes_key_wrap(&ptk.kek, &kde).expect("GTK KDE wraps");

        let mut frame = EapolKeyFrame {
            version: 1,
            desc_type: 2,
            key_info: KeyInfo(KEY_INFO_M3),
            key_length: 16,
            replay_counter,
            nonce: *anonce,
            iv: [0u8; 16],
            rsc: [0u8; 8],
            mic: [0u8; 16],
            key_data,
        };
        let encoded = frame.encode();
        let mic = crate::eapol::mic_sha1_128(&ptk.kck, &encoded);
        if tamper_mic {
            // Flip one bit in the mic to trigger verification failure.
            let mut bad_mic = mic;
            bad_mic[0] ^= 0x01;
            frame.mic = bad_mic;
        } else {
            frame.mic = mic;
        }
        frame.encode()
    }

    /// Happy-path: Init → Scanning → Authenticating → Associating → Handshake → Connected.
    #[test]
    fn happy_path() {
        let pmk = test_pmk();
        let snonce = test_snonce();
        let anonce = test_anonce();

        let mut fsm = WifiFsm::new_with_snonce(pmk, b"TestNet".to_vec(), sta_mac(), snonce);
        assert!(matches!(fsm.state(), WifiState::Init));

        // FSM starts scanning on the first event; we manually move it to Scanning.
        fsm.state = WifiState::Scanning;

        // ProbeResp with matching SSID and RSN=true.
        let bss = BssInfo {
            ssid: b"TestNet".to_vec(),
            bssid: ap_bssid(),
            channel: 6,
            rsn: true,
        };
        let actions = fsm.on_event(WifiEvent::ProbeResp(bss));
        assert!(matches!(fsm.state(), WifiState::Authenticating));
        assert!(
            actions.iter().any(|a| matches!(a, WifiAction::SendMgmt(_))),
            "ProbeResp must emit SendMgmt(auth)"
        );

        // AuthResp success.
        let actions = fsm.on_event(WifiEvent::AuthResp { status: 0 });
        assert!(matches!(fsm.state(), WifiState::Associating));
        assert!(
            actions.iter().any(|a| matches!(a, WifiAction::SendMgmt(_))),
            "AuthResp must emit SendMgmt(assoc-req)"
        );

        // AssocResp success.
        let actions = fsm.on_event(WifiEvent::AssocResp { status: 0 });
        assert!(matches!(
            fsm.state(),
            WifiState::Handshake(HandshakeStep::WaitM1)
        ));
        assert!(
            actions.is_empty(),
            "AssocResp success must produce no actions"
        );

        // EAPOL M1.
        let m1 = make_m1(&anonce, 1);
        let actions = fsm.on_event(WifiEvent::Eapol(m1));
        assert!(matches!(
            fsm.state(),
            WifiState::Handshake(HandshakeStep::WaitM3)
        ));
        assert!(
            actions
                .iter()
                .any(|a| matches!(a, WifiAction::SendEapol(_))),
            "M1 must emit SendEapol(M2)"
        );

        // EAPOL M3 (with correct MIC).
        let m3 = make_m3(&anonce, &snonce, 2, false);
        let actions = fsm.on_event(WifiEvent::Eapol(m3));
        assert!(
            matches!(fsm.state(), WifiState::Connected),
            "After M3 FSM must be Connected, was {:?}",
            fsm.state()
        );
        assert!(
            actions
                .iter()
                .any(|a| matches!(a, WifiAction::SendEapol(_))),
            "M3 must emit SendEapol(M4)"
        );
        assert!(
            actions
                .iter()
                .any(|a| matches!(a, WifiAction::InstallKey(_))),
            "M3 must emit InstallKey"
        );
        assert!(
            actions.iter().any(|a| matches!(a, WifiAction::Emit(_))),
            "M3 must emit Emit(status)"
        );
    }

    /// AssocResp with non-zero status must lead to Failed(BadRsnParams).
    #[test]
    fn assoc_status_fail() {
        let mut fsm = WifiFsm::new(test_pmk(), b"Net".to_vec(), sta_mac());
        fsm.state = WifiState::Associating;

        let actions = fsm.on_event(WifiEvent::AssocResp { status: 43 });
        assert!(
            matches!(fsm.state(), WifiState::Failed(FailReason::BadRsnParams)),
            "status 43 must → Failed(BadRsnParams)"
        );
        assert!(
            actions.iter().any(|a| matches!(a, WifiAction::Emit(_))),
            "failure must emit status"
        );
    }

    /// Timeout in Handshake state must produce SendMgmt(deauth) + Failed(HandshakeTimeout).
    #[test]
    fn handshake_timeout() {
        let mut fsm = WifiFsm::new(test_pmk(), b"Net".to_vec(), sta_mac());
        fsm.state = WifiState::Handshake(HandshakeStep::WaitM1);

        let actions = fsm.on_event(WifiEvent::Timeout);
        assert!(
            matches!(fsm.state(), WifiState::Failed(FailReason::HandshakeTimeout)),
            "Timeout must → Failed(HandshakeTimeout)"
        );
        assert!(
            actions.iter().any(|a| matches!(a, WifiAction::SendMgmt(_))),
            "Timeout must emit deauth frame"
        );
        assert!(
            actions.iter().any(|a| matches!(a, WifiAction::Emit(_))),
            "Timeout must emit status"
        );
    }

    /// M3 with a bad MIC must be silently dropped — NO InstallKey emitted.
    #[test]
    fn m3_mic_fail_no_install() {
        let pmk = test_pmk();
        let snonce = test_snonce();
        let anonce = test_anonce();

        let mut fsm = WifiFsm::new_with_snonce(pmk, b"Net".to_vec(), sta_mac(), snonce);
        // Advance to WaitM3 manually.
        fsm.state = WifiState::Handshake(HandshakeStep::WaitM3);
        fsm.bssid = Some(ap_bssid());
        let ptk = derive_ptk(&fsm.pmk, &ap_bssid(), &sta_mac(), &anonce, &snonce);
        fsm.ptk = Some(ptk);
        fsm.anonce = Some(anonce);
        fsm.snonce = Some(snonce);
        fsm.last_replay_counter = 1; // pretend M1 was received at counter=1

        // M3 with tampered MIC.
        let m3_bad = make_m3(&anonce, &snonce, 2, true);
        let actions = fsm.on_event(WifiEvent::Eapol(m3_bad));
        assert!(
            !actions
                .iter()
                .any(|a| matches!(a, WifiAction::InstallKey(_))),
            "bad M3 MIC must NOT produce InstallKey"
        );
        // State must still be WaitM3 (frame was dropped).
        assert!(
            matches!(fsm.state(), WifiState::Handshake(HandshakeStep::WaitM3)),
            "bad M3 MIC must leave FSM in WaitM3"
        );
    }

    /// Deauth while connected must emit PurgeKeys.
    #[test]
    fn disconnect_purges_keys() {
        let mut fsm = WifiFsm::new(test_pmk(), b"Net".to_vec(), sta_mac());
        fsm.state = WifiState::Connected;

        let actions = fsm.on_event(WifiEvent::Deauth);
        assert!(
            actions.iter().any(|a| matches!(a, WifiAction::PurgeKeys)),
            "Deauth must emit PurgeKeys"
        );
        assert!(
            matches!(fsm.state(), WifiState::Failed(FailReason::Deauthed)),
            "Deauth must → Failed(Deauthed)"
        );
    }

    /// The FSM must ignore EAPOL frames whose replay counter is not strictly
    /// greater than the last seen value.
    #[test]
    fn replay_counter_monotonic() {
        let mut fsm =
            WifiFsm::new_with_snonce(test_pmk(), b"Net".to_vec(), sta_mac(), test_snonce());
        fsm.state = WifiState::Handshake(HandshakeStep::WaitM1);
        fsm.bssid = Some(ap_bssid());

        // First M1 at counter=5.
        let m1_a = make_m1(&test_anonce(), 5);
        let actions = fsm.on_event(WifiEvent::Eapol(m1_a));
        assert!(!actions.is_empty(), "valid M1 must produce actions");
        assert_eq!(fsm.last_replay_counter, 5);

        // Advance state back to WaitM1 to test stale counter rejection.
        fsm.state = WifiState::Handshake(HandshakeStep::WaitM1);

        // Stale M1 at counter=3 (< 5) must be dropped.
        let m1_stale = make_m1(&test_anonce(), 3);
        let actions_stale = fsm.on_event(WifiEvent::Eapol(m1_stale));
        assert!(
            actions_stale.is_empty(),
            "stale replay counter must be dropped"
        );
        // Replay counter must not regress.
        assert_eq!(fsm.last_replay_counter, 5);
    }
}
