//! Phase 56 input-event types and wire codec.
//!
//! These types are the single source of truth for the keyboard and pointer
//! events that flow from `kbd_server` / `mouse_server` to `display_server`
//! and from `display_server` to graphical clients. Declaring them once in
//! `kernel-core` is the Phase 56 DRY discipline — no duplicated definitions
//! across `kbd_server`, `mouse_server`, `display_server`, or any client
//! library. The codec is pure logic and host-testable.
//!
//! Encoders write into a caller-supplied `&mut [u8]`; decoders take `&[u8]`
//! and return a typed [`EventCodecError`] on malformed input. Neither path
//! allocates — keyboard and pointer events are on the hot path.
//!
//! Wire layout: little-endian scalars, `#[repr(C)]` is not used because the
//! encoder serializes fields explicitly for portability across host and
//! `no_std` builds. See `KEY_EVENT_WIRE_SIZE` and `POINTER_EVENT_WIRE_SIZE`
//! for the exact byte counts.

/// Modifier-state bitmask, exactly as delivered by `kbd_server`.
///
/// `kbd_server` maintains latch/lock state (CAPS, NUM, SHIFT/CTRL/ALT/SUPER
/// held-down state) so clients never have to reconstruct it from raw key
/// edges; the bitmask is a snapshot at the time the event was produced.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub struct ModifierState(pub u16);

/// Shift held.
pub const MOD_SHIFT: u16 = 1 << 0;
/// Ctrl held.
pub const MOD_CTRL: u16 = 1 << 1;
/// Alt held.
pub const MOD_ALT: u16 = 1 << 2;
/// Super / meta held.
pub const MOD_SUPER: u16 = 1 << 3;
/// Caps Lock is currently latched.
pub const MOD_CAPS: u16 = 1 << 4;
/// Num Lock is currently latched.
pub const MOD_NUM: u16 = 1 << 5;

/// Union of all defined modifier bits. Any bit outside this mask is rejected
/// by the decoder as a typed [`EventCodecError::InvalidModifier`] so new bits
/// must be added here (and to the encoder tests) when the protocol grows.
pub const MOD_ALL: u16 = MOD_SHIFT | MOD_CTRL | MOD_ALT | MOD_SUPER | MOD_CAPS | MOD_NUM;

impl ModifierState {
    /// Empty modifier state.
    pub const fn empty() -> Self {
        Self(0)
    }

    /// Return the raw bitmask.
    pub const fn bits(self) -> u16 {
        self.0
    }

    /// True if every bit in `mask` is set.
    pub const fn contains(self, mask: u16) -> bool {
        (self.0 & mask) == mask
    }
}

/// Key-event kind: edge type of the key transition.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u8)]
pub enum KeyEventKind {
    /// Key was just pressed.
    Down = 0,
    /// Key was just released.
    Up = 1,
    /// Repeat event generated by `kbd_server` while the key is held.
    Repeat = 2,
}

/// Phase 68 Track C — left/right discrimination for modifier keys.
///
/// PS/2 sends right-side modifier scancodes prefixed with `0xE0`;
/// `kbd_server` (Phase 68 C.3) decodes the prefix and emits the
/// appropriate side. Non-modifier keys emit
/// [`ModifierSide::Either`] — the side designation only carries
/// meaning for the `Shift` / `Ctrl` / `Alt` / `Super` key edges
/// themselves.
///
/// A version-1 client (announcing `PROTOCOL_VERSION = 1` in its
/// `ClientMessage::Hello`) sees every `KeyEvent` with
/// [`ModifierSide::Either`] via a compatibility shim implemented in
/// `kernel_core::input::events::downgrade_for_v1_client`.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
#[repr(u8)]
pub enum ModifierSide {
    /// Left-side modifier (bare scancode on PS/2: `0x2A` / `0x1D` /
    /// `0x38` for Shift / Ctrl / Alt).
    Left = 0,
    /// Right-side modifier (`0xE0`-prefixed PS/2 scancode: `0xE0 0x36`
    /// / `0xE0 0x1D` / `0xE0 0x38`). Note: right-Shift's bare
    /// scancode is `0x36` rather than the `0xE0 0x2A` form used by
    /// some sources — see the PS/2 scan-set 1 reference for the
    /// canonical mapping.
    Right = 1,
    /// No side designation. Emitted for non-modifier keys, by the
    /// version-1 compatibility shim for all keys, and by the
    /// `InjectKey` test-only verb (which does not synthesize a
    /// side-aware scancode).
    #[default]
    Either = 2,
}

impl ModifierSide {
    /// Phase 68 Track C — map a hardware-neutral keycode to its side
    /// designation. Left modifier keycodes return [`Self::Left`];
    /// right modifier keycodes return [`Self::Right`]; everything
    /// else returns [`Self::Either`]. `kbd_server::feed_byte` calls
    /// this helper after `ScancodeDecoder` decodes the
    /// `0xE0`-prefixed extended scancode into the appropriate
    /// `KEY_RCTRL` / `KEY_RALT` / `KEY_RSHIFT` keycode.
    pub fn for_keycode(keycode: u32) -> Self {
        // The keycode constants are defined in `crate::input::keymap`;
        // mirror their numeric values here so this helper does not
        // pull in the keymap module (the keymap module imports
        // `KeyEvent` from this file).
        const KEY_LSHIFT: u32 = 0x0080;
        const KEY_RSHIFT: u32 = 0x0081;
        const KEY_LCTRL: u32 = 0x0082;
        const KEY_RCTRL: u32 = 0x0083;
        const KEY_LALT: u32 = 0x0084;
        const KEY_RALT: u32 = 0x0085;
        match keycode {
            KEY_LSHIFT | KEY_LCTRL | KEY_LALT => Self::Left,
            KEY_RSHIFT | KEY_RCTRL | KEY_RALT => Self::Right,
            _ => Self::Either,
        }
    }
}

/// Hardware-neutral key event after scancode translation and keymap lookup.
///
/// `keycode` is the `kbd_server`-internal hardware-neutral keycode (stable
/// across scancode-set and USB-HID sources). `symbol` is the post-keymap
/// code point (Unicode scalar for printable symbols; a `kernel-core`-defined
/// constant in the private-use area for function/arrow/modifier keys).
/// `modifiers` is the latched/held modifier snapshot at event time.
///
/// Phase 68 Track C added `modifier_side`. Non-modifier keys emit
/// [`ModifierSide::Either`]; version-1 clients see every
/// `KeyEvent` with `Either` via the downgrade shim.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct KeyEvent {
    pub timestamp_ms: u64,
    pub keycode: u32,
    pub symbol: u32,
    pub modifiers: ModifierState,
    pub kind: KeyEventKind,
    /// Phase 68 — left vs. right side of the originating physical
    /// key. See [`ModifierSide`].
    pub modifier_side: ModifierSide,
}

/// Exact serialized byte count of a [`KeyEvent`].
///
/// Phase 68 grew the wire size from 19 to 20 bytes when the
/// `modifier_side` field was added.
pub const KEY_EVENT_WIRE_SIZE: usize = 8 + 4 + 4 + 2 + 1 + 1;

/// Pre-Phase-68 (`PROTOCOL_VERSION = 1`) wire size of a
/// [`KeyEvent`]. The version-1 compatibility shim decodes the
/// legacy layout and synthesizes [`ModifierSide::Either`].
pub const KEY_EVENT_WIRE_SIZE_V1: usize = 8 + 4 + 4 + 2 + 1;

/// Phase 68 Track C — produce a copy of `ev` suitable for sending to
/// a client that handshook at `PROTOCOL_VERSION = 1`. The shim
/// replaces `modifier_side` with [`ModifierSide::Either`] so the
/// caller can encode using the legacy 19-byte layout without losing
/// information the v1 client could not decode anyway.
pub fn downgrade_for_v1_client(ev: KeyEvent) -> KeyEvent {
    KeyEvent {
        modifier_side: ModifierSide::Either,
        ..ev
    }
}

/// Pointer button transition attached to a [`PointerEvent`].
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub enum PointerButton {
    /// The event carries motion/wheel only; no button edge.
    #[default]
    None,
    /// Button `index` just went down.
    Down(u8),
    /// Button `index` just went up.
    Up(u8),
}

/// Pointer event, as emitted by `mouse_server`.
///
/// `dx` / `dy` are relative deltas from the physical source (PS/2 AUX on
/// Phase 56). `abs_position` carries the compositor-maintained absolute
/// cursor position when the source can supply it; pure relative sources
/// encode `None` here.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct PointerEvent {
    pub timestamp_ms: u64,
    pub dx: i32,
    pub dy: i32,
    pub abs_position: Option<(i32, i32)>,
    pub button: PointerButton,
    pub wheel_dx: i32,
    pub wheel_dy: i32,
    pub modifiers: ModifierState,
}

/// Exact serialized byte count of a [`PointerEvent`].
///
/// Layout (LE): `timestamp_ms(8) + dx(4) + dy(4) + abs_flag(1) + abs_x(4) +
/// abs_y(4) + button_tag(1) + button_index(1) + wheel_dx(4) + wheel_dy(4) +
/// modifiers(2) = 37`.
pub const POINTER_EVENT_WIRE_SIZE: usize = 8 + 4 + 4 + 1 + 4 + 4 + 1 + 1 + 4 + 4 + 2;

/// Errors emitted by the input-event codec.
///
/// Variants are *data*, not strings, so callers can pattern-match and
/// recover. `#[non_exhaustive]` so follow-up phases may extend the set
/// without forcing downstream crates into exhaustive matches.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[non_exhaustive]
pub enum EventCodecError {
    /// Buffer is too small to hold the encoded form or smaller than the
    /// fixed serialized size of the message being decoded.
    Truncated,
    /// Modifier bitmask contained bits outside [`MOD_ALL`].
    InvalidModifier,
    /// `KeyEventKind` tag was not one of the defined variants.
    InvalidKeyKind,
    /// Pointer-button tag was not one of the defined variants.
    InvalidButtonTag,
    /// Absolute-position flag was neither 0 nor 1.
    InvalidAbsFlag,
    /// Phase 68 Track C — `ModifierSide` tag was not one of the
    /// defined variants (`Left=0`, `Right=1`, `Either=2`).
    InvalidModifierSide,
}

impl KeyEvent {
    /// Encode into a caller-supplied buffer. Returns the number of bytes
    /// written on success. Never allocates.
    ///
    /// Phase 68 wire format (20 bytes): `timestamp_ms (u64) | keycode
    /// (u32) | symbol (u32) | modifiers (u16) | kind (u8) |
    /// modifier_side (u8)`. The v1 layout (19 bytes) is accessible via
    /// [`Self::encode_v1`] for the version-1 compatibility shim.
    pub fn encode(&self, buf: &mut [u8]) -> Result<usize, EventCodecError> {
        if buf.len() < KEY_EVENT_WIRE_SIZE {
            return Err(EventCodecError::Truncated);
        }
        if (self.modifiers.0 & !MOD_ALL) != 0 {
            return Err(EventCodecError::InvalidModifier);
        }
        buf[0..8].copy_from_slice(&self.timestamp_ms.to_le_bytes());
        buf[8..12].copy_from_slice(&self.keycode.to_le_bytes());
        buf[12..16].copy_from_slice(&self.symbol.to_le_bytes());
        buf[16..18].copy_from_slice(&self.modifiers.0.to_le_bytes());
        buf[18] = self.kind as u8;
        buf[19] = self.modifier_side as u8;
        Ok(KEY_EVENT_WIRE_SIZE)
    }

    /// Decode a [`KeyEvent`] from the start of `buf`. Returns the event and
    /// the number of bytes consumed.
    pub fn decode(buf: &[u8]) -> Result<(Self, usize), EventCodecError> {
        if buf.len() < KEY_EVENT_WIRE_SIZE {
            return Err(EventCodecError::Truncated);
        }
        let timestamp_ms = u64::from_le_bytes(array8(&buf[0..8]));
        let keycode = u32::from_le_bytes(array4(&buf[8..12]));
        let symbol = u32::from_le_bytes(array4(&buf[12..16]));
        let mod_bits = u16::from_le_bytes(array2(&buf[16..18]));
        if (mod_bits & !MOD_ALL) != 0 {
            return Err(EventCodecError::InvalidModifier);
        }
        let kind = match buf[18] {
            0 => KeyEventKind::Down,
            1 => KeyEventKind::Up,
            2 => KeyEventKind::Repeat,
            _ => return Err(EventCodecError::InvalidKeyKind),
        };
        let modifier_side = match buf[19] {
            0 => ModifierSide::Left,
            1 => ModifierSide::Right,
            2 => ModifierSide::Either,
            _ => return Err(EventCodecError::InvalidModifierSide),
        };
        Ok((
            Self {
                timestamp_ms,
                keycode,
                symbol,
                modifiers: ModifierState(mod_bits),
                kind,
                modifier_side,
            },
            KEY_EVENT_WIRE_SIZE,
        ))
    }

    /// Encode using the pre-Phase-68 19-byte layout for a version-1
    /// client. `modifier_side` is implicitly [`ModifierSide::Either`]
    /// on the wire — the v1 layout never carried the field.
    pub fn encode_v1(&self, buf: &mut [u8]) -> Result<usize, EventCodecError> {
        if buf.len() < KEY_EVENT_WIRE_SIZE_V1 {
            return Err(EventCodecError::Truncated);
        }
        if (self.modifiers.0 & !MOD_ALL) != 0 {
            return Err(EventCodecError::InvalidModifier);
        }
        buf[0..8].copy_from_slice(&self.timestamp_ms.to_le_bytes());
        buf[8..12].copy_from_slice(&self.keycode.to_le_bytes());
        buf[12..16].copy_from_slice(&self.symbol.to_le_bytes());
        buf[16..18].copy_from_slice(&self.modifiers.0.to_le_bytes());
        buf[18] = self.kind as u8;
        Ok(KEY_EVENT_WIRE_SIZE_V1)
    }

    /// Decode using the pre-Phase-68 19-byte layout. Sets
    /// `modifier_side` to [`ModifierSide::Either`] — the shim
    /// contract that lets a Phase 56 capture stream feed a Phase 68
    /// consumer.
    pub fn decode_v1(buf: &[u8]) -> Result<(Self, usize), EventCodecError> {
        if buf.len() < KEY_EVENT_WIRE_SIZE_V1 {
            return Err(EventCodecError::Truncated);
        }
        let timestamp_ms = u64::from_le_bytes(array8(&buf[0..8]));
        let keycode = u32::from_le_bytes(array4(&buf[8..12]));
        let symbol = u32::from_le_bytes(array4(&buf[12..16]));
        let mod_bits = u16::from_le_bytes(array2(&buf[16..18]));
        if (mod_bits & !MOD_ALL) != 0 {
            return Err(EventCodecError::InvalidModifier);
        }
        let kind = match buf[18] {
            0 => KeyEventKind::Down,
            1 => KeyEventKind::Up,
            2 => KeyEventKind::Repeat,
            _ => return Err(EventCodecError::InvalidKeyKind),
        };
        Ok((
            Self {
                timestamp_ms,
                keycode,
                symbol,
                modifiers: ModifierState(mod_bits),
                kind,
                modifier_side: ModifierSide::Either,
            },
            KEY_EVENT_WIRE_SIZE_V1,
        ))
    }
}

impl PointerEvent {
    /// Encode into a caller-supplied buffer. Never allocates.
    pub fn encode(&self, buf: &mut [u8]) -> Result<usize, EventCodecError> {
        if buf.len() < POINTER_EVENT_WIRE_SIZE {
            return Err(EventCodecError::Truncated);
        }
        if (self.modifiers.0 & !MOD_ALL) != 0 {
            return Err(EventCodecError::InvalidModifier);
        }
        buf[0..8].copy_from_slice(&self.timestamp_ms.to_le_bytes());
        buf[8..12].copy_from_slice(&self.dx.to_le_bytes());
        buf[12..16].copy_from_slice(&self.dy.to_le_bytes());
        let (abs_flag, abs_x, abs_y) = match self.abs_position {
            Some((x, y)) => (1u8, x, y),
            None => (0u8, 0i32, 0i32),
        };
        buf[16] = abs_flag;
        buf[17..21].copy_from_slice(&abs_x.to_le_bytes());
        buf[21..25].copy_from_slice(&abs_y.to_le_bytes());
        let (btn_tag, btn_index) = match self.button {
            PointerButton::None => (0u8, 0u8),
            PointerButton::Down(i) => (1u8, i),
            PointerButton::Up(i) => (2u8, i),
        };
        buf[25] = btn_tag;
        buf[26] = btn_index;
        buf[27..31].copy_from_slice(&self.wheel_dx.to_le_bytes());
        buf[31..35].copy_from_slice(&self.wheel_dy.to_le_bytes());
        buf[35..37].copy_from_slice(&self.modifiers.0.to_le_bytes());
        Ok(POINTER_EVENT_WIRE_SIZE)
    }

    /// Decode a [`PointerEvent`] from the start of `buf`.
    pub fn decode(buf: &[u8]) -> Result<(Self, usize), EventCodecError> {
        if buf.len() < POINTER_EVENT_WIRE_SIZE {
            return Err(EventCodecError::Truncated);
        }
        let timestamp_ms = u64::from_le_bytes(array8(&buf[0..8]));
        let dx = i32::from_le_bytes(array4(&buf[8..12]));
        let dy = i32::from_le_bytes(array4(&buf[12..16]));
        let abs_flag = buf[16];
        let abs_x = i32::from_le_bytes(array4(&buf[17..21]));
        let abs_y = i32::from_le_bytes(array4(&buf[21..25]));
        let abs_position = match abs_flag {
            0 => None,
            1 => Some((abs_x, abs_y)),
            _ => return Err(EventCodecError::InvalidAbsFlag),
        };
        let btn_tag = buf[25];
        let btn_index = buf[26];
        let button = match btn_tag {
            0 => PointerButton::None,
            1 => PointerButton::Down(btn_index),
            2 => PointerButton::Up(btn_index),
            _ => return Err(EventCodecError::InvalidButtonTag),
        };
        let wheel_dx = i32::from_le_bytes(array4(&buf[27..31]));
        let wheel_dy = i32::from_le_bytes(array4(&buf[31..35]));
        let mod_bits = u16::from_le_bytes(array2(&buf[35..37]));
        if (mod_bits & !MOD_ALL) != 0 {
            return Err(EventCodecError::InvalidModifier);
        }
        Ok((
            Self {
                timestamp_ms,
                dx,
                dy,
                abs_position,
                button,
                wheel_dx,
                wheel_dy,
                modifiers: ModifierState(mod_bits),
            },
            POINTER_EVENT_WIRE_SIZE,
        ))
    }
}

fn array2(slice: &[u8]) -> [u8; 2] {
    [slice[0], slice[1]]
}

fn array4(slice: &[u8]) -> [u8; 4] {
    [slice[0], slice[1], slice[2], slice[3]]
}

fn array8(slice: &[u8]) -> [u8; 8] {
    [
        slice[0], slice[1], slice[2], slice[3], slice[4], slice[5], slice[6], slice[7],
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    // ---- KeyEvent round-trip -------------------------------------------

    #[test]
    fn key_event_down_round_trips() {
        let ev = KeyEvent {
            timestamp_ms: 0x1234_5678_9abc_def0,
            keycode: 0x30,
            symbol: b'a' as u32,
            modifiers: ModifierState(MOD_SHIFT | MOD_CTRL),
            kind: KeyEventKind::Down,
            modifier_side: ModifierSide::Left,
        };
        let mut buf = [0u8; KEY_EVENT_WIRE_SIZE];
        let n = ev.encode(&mut buf).expect("encode");
        assert_eq!(n, KEY_EVENT_WIRE_SIZE);
        let (back, consumed) = KeyEvent::decode(&buf).expect("decode");
        assert_eq!(consumed, KEY_EVENT_WIRE_SIZE);
        assert_eq!(back, ev);
    }

    #[test]
    fn key_event_up_round_trips() {
        let ev = KeyEvent {
            timestamp_ms: 0,
            keycode: u32::MAX,
            symbol: 0,
            modifiers: ModifierState(MOD_ALL),
            kind: KeyEventKind::Up,
            modifier_side: ModifierSide::Right,
        };
        let mut buf = [0u8; KEY_EVENT_WIRE_SIZE];
        ev.encode(&mut buf).expect("encode");
        let (back, _) = KeyEvent::decode(&buf).expect("decode");
        assert_eq!(back, ev);
    }

    #[test]
    fn key_event_repeat_round_trips() {
        let ev = KeyEvent {
            timestamp_ms: 42,
            keycode: 0x0d,
            symbol: 0x0a,
            modifiers: ModifierState::empty(),
            kind: KeyEventKind::Repeat,
            modifier_side: ModifierSide::Either,
        };
        let mut buf = [0u8; KEY_EVENT_WIRE_SIZE];
        ev.encode(&mut buf).unwrap();
        assert_eq!(KeyEvent::decode(&buf).unwrap().0, ev);
    }

    #[test]
    fn key_event_short_buffer_returns_truncated() {
        let ev = KeyEvent {
            timestamp_ms: 0,
            keycode: 0,
            symbol: 0,
            modifiers: ModifierState::empty(),
            kind: KeyEventKind::Down,
            modifier_side: ModifierSide::Either,
        };
        let mut tiny = [0u8; KEY_EVENT_WIRE_SIZE - 1];
        assert_eq!(ev.encode(&mut tiny), Err(EventCodecError::Truncated));
        let tiny_in = [0u8; KEY_EVENT_WIRE_SIZE - 1];
        assert_eq!(KeyEvent::decode(&tiny_in), Err(EventCodecError::Truncated));
    }

    #[test]
    fn key_event_rejects_unknown_kind_tag() {
        let mut buf = [0u8; KEY_EVENT_WIRE_SIZE];
        buf[18] = 7;
        assert_eq!(
            KeyEvent::decode(&buf).unwrap_err(),
            EventCodecError::InvalidKeyKind
        );
    }

    // Phase 68 Track C — `ModifierSide` round-trips left/right via the
    // 20-byte layout, and an invalid tag is rejected with a typed
    // error (the version-1 shim never produces this byte).
    #[test]
    fn key_event_modifier_side_left_round_trips() {
        let ev = KeyEvent {
            timestamp_ms: 1,
            keycode: 0x2A,
            symbol: 0,
            modifiers: ModifierState(MOD_SHIFT),
            kind: KeyEventKind::Down,
            modifier_side: ModifierSide::Left,
        };
        let mut buf = [0u8; KEY_EVENT_WIRE_SIZE];
        ev.encode(&mut buf).unwrap();
        let (back, _) = KeyEvent::decode(&buf).unwrap();
        assert_eq!(back.modifier_side, ModifierSide::Left);
    }

    #[test]
    fn key_event_modifier_side_right_round_trips() {
        let ev = KeyEvent {
            timestamp_ms: 1,
            keycode: 0x36,
            symbol: 0,
            modifiers: ModifierState(MOD_SHIFT),
            kind: KeyEventKind::Down,
            modifier_side: ModifierSide::Right,
        };
        let mut buf = [0u8; KEY_EVENT_WIRE_SIZE];
        ev.encode(&mut buf).unwrap();
        let (back, _) = KeyEvent::decode(&buf).unwrap();
        assert_eq!(back.modifier_side, ModifierSide::Right);
    }

    #[test]
    fn key_event_rejects_unknown_modifier_side_tag() {
        let mut buf = [0u8; KEY_EVENT_WIRE_SIZE];
        buf[19] = 9;
        assert_eq!(
            KeyEvent::decode(&buf).unwrap_err(),
            EventCodecError::InvalidModifierSide
        );
    }

    // Phase 68 Track C — version-1 compatibility shim: a v1 client
    // captures the 19-byte legacy layout; the shim decode produces a
    // `KeyEvent` with `modifier_side: Either` so downstream consumers
    // see a Phase 68-shaped record.
    #[test]
    fn key_event_v1_decode_yields_either_side() {
        let original = KeyEvent {
            timestamp_ms: 7,
            keycode: 0x1D,
            symbol: 0,
            modifiers: ModifierState(MOD_CTRL),
            kind: KeyEventKind::Down,
            modifier_side: ModifierSide::Right,
        };
        let mut buf = [0u8; KEY_EVENT_WIRE_SIZE_V1];
        original.encode_v1(&mut buf).unwrap();
        let (back, consumed) = KeyEvent::decode_v1(&buf).unwrap();
        assert_eq!(consumed, KEY_EVENT_WIRE_SIZE_V1);
        assert_eq!(back.modifier_side, ModifierSide::Either);
        assert_eq!(back.keycode, original.keycode);
        assert_eq!(back.kind, original.kind);
    }

    #[test]
    fn downgrade_for_v1_client_strips_side() {
        let original = KeyEvent {
            timestamp_ms: 0,
            keycode: 0,
            symbol: 0,
            modifiers: ModifierState::empty(),
            kind: KeyEventKind::Down,
            modifier_side: ModifierSide::Left,
        };
        let downgraded = downgrade_for_v1_client(original);
        assert_eq!(downgraded.modifier_side, ModifierSide::Either);
        assert_eq!(downgraded.keycode, original.keycode);
        assert_eq!(downgraded.kind, original.kind);
    }

    // Phase 68 Track C — `ModifierSide::for_keycode` maps the keymap's
    // left/right modifier keycodes to the correct side; non-modifier
    // keys default to `Either`. The constants mirror the values in
    // `crate::input::keymap` so this test pins the contract.
    #[test]
    fn modifier_side_for_left_keycodes() {
        assert_eq!(ModifierSide::for_keycode(0x0080), ModifierSide::Left); // KEY_LSHIFT
        assert_eq!(ModifierSide::for_keycode(0x0082), ModifierSide::Left); // KEY_LCTRL
        assert_eq!(ModifierSide::for_keycode(0x0084), ModifierSide::Left); // KEY_LALT
    }

    #[test]
    fn modifier_side_for_right_keycodes() {
        assert_eq!(ModifierSide::for_keycode(0x0081), ModifierSide::Right); // KEY_RSHIFT
        assert_eq!(ModifierSide::for_keycode(0x0083), ModifierSide::Right); // KEY_RCTRL
        assert_eq!(ModifierSide::for_keycode(0x0085), ModifierSide::Right); // KEY_RALT
    }

    #[test]
    fn modifier_side_for_non_modifier_is_either() {
        assert_eq!(ModifierSide::for_keycode(0x001E), ModifierSide::Either); // KEY_A
        assert_eq!(ModifierSide::for_keycode(0x0039), ModifierSide::Either); // KEY_SPACE
        assert_eq!(ModifierSide::for_keycode(0), ModifierSide::Either);
    }

    #[test]
    fn key_event_rejects_unknown_modifier_bit() {
        let mut buf = [0u8; KEY_EVENT_WIRE_SIZE];
        let bad = MOD_ALL | (1 << 15);
        buf[16..18].copy_from_slice(&bad.to_le_bytes());
        assert_eq!(
            KeyEvent::decode(&buf).unwrap_err(),
            EventCodecError::InvalidModifier
        );
    }

    // ---- PointerEvent round-trip ---------------------------------------

    #[test]
    fn pointer_event_motion_only_round_trips() {
        let ev = PointerEvent {
            timestamp_ms: 100,
            dx: -3,
            dy: 4,
            abs_position: None,
            button: PointerButton::None,
            wheel_dx: 0,
            wheel_dy: 0,
            modifiers: ModifierState::empty(),
        };
        let mut buf = [0u8; POINTER_EVENT_WIRE_SIZE];
        ev.encode(&mut buf).unwrap();
        let (back, n) = PointerEvent::decode(&buf).unwrap();
        assert_eq!(back, ev);
        assert_eq!(n, POINTER_EVENT_WIRE_SIZE);
    }

    #[test]
    fn pointer_event_with_absolute_position_round_trips() {
        let ev = PointerEvent {
            timestamp_ms: 500,
            dx: 0,
            dy: 0,
            abs_position: Some((1920, 1080)),
            button: PointerButton::None,
            wheel_dx: 0,
            wheel_dy: 0,
            modifiers: ModifierState::empty(),
        };
        let mut buf = [0u8; POINTER_EVENT_WIRE_SIZE];
        ev.encode(&mut buf).unwrap();
        assert_eq!(PointerEvent::decode(&buf).unwrap().0, ev);
    }

    #[test]
    fn pointer_event_button_down_round_trips() {
        let ev = PointerEvent {
            timestamp_ms: 1,
            dx: 0,
            dy: 0,
            abs_position: Some((10, 20)),
            button: PointerButton::Down(1),
            wheel_dx: 0,
            wheel_dy: 0,
            modifiers: ModifierState(MOD_CTRL),
        };
        let mut buf = [0u8; POINTER_EVENT_WIRE_SIZE];
        ev.encode(&mut buf).unwrap();
        assert_eq!(PointerEvent::decode(&buf).unwrap().0, ev);
    }

    #[test]
    fn pointer_event_button_up_round_trips() {
        let ev = PointerEvent {
            timestamp_ms: 2,
            dx: 1,
            dy: -1,
            abs_position: Some((0, 0)),
            button: PointerButton::Up(3),
            wheel_dx: 0,
            wheel_dy: 0,
            modifiers: ModifierState::empty(),
        };
        let mut buf = [0u8; POINTER_EVENT_WIRE_SIZE];
        ev.encode(&mut buf).unwrap();
        assert_eq!(PointerEvent::decode(&buf).unwrap().0, ev);
    }

    #[test]
    fn pointer_event_wheel_round_trips() {
        let ev = PointerEvent {
            timestamp_ms: 0,
            dx: 0,
            dy: 0,
            abs_position: None,
            button: PointerButton::None,
            wheel_dx: 3,
            wheel_dy: -7,
            modifiers: ModifierState::empty(),
        };
        let mut buf = [0u8; POINTER_EVENT_WIRE_SIZE];
        ev.encode(&mut buf).unwrap();
        assert_eq!(PointerEvent::decode(&buf).unwrap().0, ev);
    }

    #[test]
    fn pointer_event_rejects_invalid_abs_flag() {
        let mut buf = [0u8; POINTER_EVENT_WIRE_SIZE];
        buf[16] = 5;
        assert_eq!(
            PointerEvent::decode(&buf).unwrap_err(),
            EventCodecError::InvalidAbsFlag
        );
    }

    #[test]
    fn pointer_event_rejects_invalid_button_tag() {
        let mut buf = [0u8; POINTER_EVENT_WIRE_SIZE];
        buf[25] = 9;
        assert_eq!(
            PointerEvent::decode(&buf).unwrap_err(),
            EventCodecError::InvalidButtonTag
        );
    }

    #[test]
    fn pointer_event_short_buffer_returns_truncated() {
        let tiny = [0u8; POINTER_EVENT_WIRE_SIZE - 1];
        assert_eq!(
            PointerEvent::decode(&tiny).unwrap_err(),
            EventCodecError::Truncated
        );
    }

    // ---- Property tests ------------------------------------------------

    fn arb_key_kind() -> impl Strategy<Value = KeyEventKind> {
        prop_oneof![
            Just(KeyEventKind::Down),
            Just(KeyEventKind::Up),
            Just(KeyEventKind::Repeat),
        ]
    }

    fn arb_modifier_state() -> impl Strategy<Value = ModifierState> {
        (0u16..=MOD_ALL).prop_map(|bits| ModifierState(bits & MOD_ALL))
    }

    fn arb_modifier_side() -> impl Strategy<Value = ModifierSide> {
        prop_oneof![
            Just(ModifierSide::Left),
            Just(ModifierSide::Right),
            Just(ModifierSide::Either),
        ]
    }

    fn arb_key_event() -> impl Strategy<Value = KeyEvent> {
        (
            any::<u64>(),
            any::<u32>(),
            any::<u32>(),
            arb_modifier_state(),
            arb_key_kind(),
            arb_modifier_side(),
        )
            .prop_map(
                |(timestamp_ms, keycode, symbol, modifiers, kind, modifier_side)| KeyEvent {
                    timestamp_ms,
                    keycode,
                    symbol,
                    modifiers,
                    kind,
                    modifier_side,
                },
            )
    }

    fn arb_button() -> impl Strategy<Value = PointerButton> {
        prop_oneof![
            Just(PointerButton::None),
            any::<u8>().prop_map(PointerButton::Down),
            any::<u8>().prop_map(PointerButton::Up),
        ]
    }

    fn arb_pointer_event() -> impl Strategy<Value = PointerEvent> {
        (
            any::<u64>(),
            any::<i32>(),
            any::<i32>(),
            prop::option::of((any::<i32>(), any::<i32>())),
            arb_button(),
            any::<i32>(),
            any::<i32>(),
            arb_modifier_state(),
        )
            .prop_map(
                |(timestamp_ms, dx, dy, abs_position, button, wheel_dx, wheel_dy, modifiers)| {
                    PointerEvent {
                        timestamp_ms,
                        dx,
                        dy,
                        abs_position,
                        button,
                        wheel_dx,
                        wheel_dy,
                        modifiers,
                    }
                },
            )
    }

    proptest! {
        #[test]
        fn prop_key_event_round_trips(ev in arb_key_event()) {
            let mut buf = [0u8; KEY_EVENT_WIRE_SIZE];
            ev.encode(&mut buf).expect("encode");
            let (back, n) = KeyEvent::decode(&buf).expect("decode");
            prop_assert_eq!(n, KEY_EVENT_WIRE_SIZE);
            prop_assert_eq!(back, ev);
        }

        #[test]
        fn prop_pointer_event_round_trips(ev in arb_pointer_event()) {
            let mut buf = [0u8; POINTER_EVENT_WIRE_SIZE];
            ev.encode(&mut buf).expect("encode");
            let (back, n) = PointerEvent::decode(&buf).expect("decode");
            prop_assert_eq!(n, POINTER_EVENT_WIRE_SIZE);
            prop_assert_eq!(back, ev);
        }

        #[test]
        fn prop_key_event_decode_never_panics(bytes in prop::collection::vec(any::<u8>(), 0..128)) {
            let _ = KeyEvent::decode(&bytes);
        }

        #[test]
        fn prop_pointer_event_decode_never_panics(bytes in prop::collection::vec(any::<u8>(), 0..128)) {
            let _ = PointerEvent::decode(&bytes);
        }
    }
}
