//! Phase 69b Tracks C/D/E — Latin-1 supplement and Unicode box-drawing
//! bitmap glyph tables, plus the unified [`resolve_glyph`] accessor.
//!
//! ## Coverage
//!
//! - **U+0020..=U+007F** — ASCII printables. Resolved against the
//!   existing [`crate::session::font_data::GLYPH_BITMAPS`] table.
//! - **U+0080..=U+00FF** — Latin-1 supplement. Covered by the
//!   [`LATIN1_GLYPHS`] table below. C1 control characters
//!   (U+0080..=U+009F) plus U+00A0 (NBSP) render as a blank cell —
//!   exactly the "no inked pixels" behaviour every terminal applies
//!   to control codes.
//! - **U+2500..=U+257F** — Unicode box-drawing block. Covered by the
//!   [`BOX_DRAWING_GLYPHS`] table.
//! - **Everything else** — the centred-dot fallback glyph
//!   [`FALLBACK_DOT_GLYPH`], matching the Phase 69b design's "single
//!   replacement glyph" rule.
//!
//! ## Provenance
//!
//! - ASCII glyphs (out of scope here, see `font_data.rs`) come from
//!   the public-domain IBM VGA BIOS 8×16 font.
//! - Latin-1 glyphs are procedurally generated by overlaying base
//!   ASCII letters with diacritic marks for the
//!   "letter + accent" codepoints, and by hand-tuned 8×16 bitmaps for
//!   non-letter symbols. The generation lives entirely in
//!   `const fn`s — no runtime cost, no external data file.
//! - Box-drawing glyphs are procedurally generated from a per-
//!   codepoint edge spec `(north, east, south, west)` where each edge
//!   carries one of [`EdgeKind::None`], [`EdgeKind::Light`],
//!   [`EdgeKind::Heavy`], or [`EdgeKind::Double`]. Specials such as
//!   arcs (U+256D..=U+2570), diagonals + X (U+2571..=U+2573), and
//!   half-line endpoints (U+2574..=U+257F) are handled by explicit
//!   case arms.
//!
//! ## Cell size
//!
//! All glyphs use the same 8×16 cell as the existing ASCII font so the
//! resolver can hand back any of them through a single
//! [`crate::session::font::Glyph`] type. The font's cell size is fixed
//! for the lifetime of the font instance; Phase 69c is where wider
//! tables (TTF) will land.

use super::font::Glyph;
use super::font_data::{ASCII_FIRST, ASCII_LAST, CELL_HEIGHT, CELL_WIDTH, GLYPH_BITMAPS};

/// First codepoint in the Latin-1 supplement block.
pub const LATIN1_FIRST: u32 = 0x0080;
/// Last codepoint in the Latin-1 supplement block.
pub const LATIN1_LAST: u32 = 0x00FF;
/// First codepoint in the Unicode box-drawing block.
pub const BOX_DRAWING_FIRST: u32 = 0x2500;
/// Last codepoint in the Unicode box-drawing block.
pub const BOX_DRAWING_LAST: u32 = 0x257F;

/// Number of glyphs in each extended table (128 entries each).
const LATIN1_COUNT: usize = (LATIN1_LAST - LATIN1_FIRST + 1) as usize;
const BOX_DRAWING_COUNT: usize = (BOX_DRAWING_LAST - BOX_DRAWING_FIRST + 1) as usize;

/// Bytes per glyph (cell height in pixels, 1 byte per row).
const BYTES_PER_GLYPH: usize = CELL_HEIGHT as usize;

// ---------------------------------------------------------------------------
// Latin-1 supplement bitmaps
// ---------------------------------------------------------------------------

/// 16-byte bitmap of all zeros — used for the C1 control range
/// (U+0080..=U+009F) and the no-break space (U+00A0). Terminals never
/// paint control characters; this matches that contract.
static BLANK: [u8; BYTES_PER_GLYPH] = [0; BYTES_PER_GLYPH];

/// Build the Latin-1 supplement bitmap table at compile time.
const fn build_latin1_bitmaps() -> [[u8; BYTES_PER_GLYPH]; LATIN1_COUNT] {
    let mut out = [[0u8; BYTES_PER_GLYPH]; LATIN1_COUNT];
    let mut i: usize = 0;
    while i < LATIN1_COUNT {
        let codepoint = LATIN1_FIRST + i as u32;
        out[i] = latin1_bitmap_for(codepoint);
        i += 1;
    }
    out
}

/// Compute the 16-byte bitmap for a single Latin-1 codepoint.
const fn latin1_bitmap_for(codepoint: u32) -> [u8; BYTES_PER_GLYPH] {
    // C1 control range plus NBSP render blank.
    if codepoint <= 0x9F || codepoint == 0xA0 {
        return [0; BYTES_PER_GLYPH];
    }
    match codepoint {
        // Latin-1 symbols. Each bitmap is hand-tuned in the same 8×16
        // shape as the ASCII font.
        0xA1 => bitmap(&[
            0x00, 0x00, 0x18, 0x18, 0x00, 0x18, 0x18, 0x18, 0x18, 0x3C, 0x3C, 0x18, 0x00, 0x00,
            0x00, 0x00,
        ]), // ¡ inverted exclamation
        0xA2 => bitmap(&[
            0x00, 0x00, 0x08, 0x1C, 0x36, 0x60, 0x60, 0x60, 0x36, 0x1C, 0x08, 0x10, 0x00, 0x00,
            0x00, 0x00,
        ]), // ¢ cent sign
        0xA3 => bitmap(&[
            0x00, 0x00, 0x1C, 0x36, 0x30, 0x30, 0x78, 0x30, 0x30, 0x30, 0x73, 0xFE, 0x00, 0x00,
            0x00, 0x00,
        ]), // £ pound sign
        0xA4 => bitmap(&[
            0x00, 0x00, 0x00, 0x00, 0x66, 0x3C, 0x66, 0x66, 0x66, 0x3C, 0x66, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ¤ currency sign
        0xA5 => bitmap(&[
            0x00, 0x00, 0xC3, 0xC3, 0x66, 0x3C, 0x18, 0x7E, 0x18, 0x7E, 0x18, 0x18, 0x00, 0x00,
            0x00, 0x00,
        ]), // ¥ yen sign
        0xA6 => bitmap(&[
            0x00, 0x00, 0x18, 0x18, 0x18, 0x18, 0x00, 0x00, 0x00, 0x18, 0x18, 0x18, 0x18, 0x00,
            0x00, 0x00,
        ]), // ¦ broken bar
        0xA7 => bitmap(&[
            0x00, 0x3C, 0x66, 0x60, 0x3C, 0x66, 0xC6, 0xC6, 0x66, 0x3C, 0x06, 0x66, 0x3C, 0x00,
            0x00, 0x00,
        ]), // § section sign
        0xA8 => bitmap(&[
            0x00, 0x66, 0x66, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ¨ diaeresis
        0xA9 => bitmap(&[
            0x00, 0x00, 0x3C, 0x42, 0x99, 0xA5, 0xA1, 0xA1, 0xA5, 0x99, 0x42, 0x3C, 0x00, 0x00,
            0x00, 0x00,
        ]), // © copyright sign
        0xAA => bitmap(&[
            0x00, 0x1C, 0x36, 0x36, 0x1C, 0x00, 0x3E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ª feminine ordinal
        0xAB => bitmap(&[
            0x00, 0x00, 0x00, 0x00, 0x36, 0x6C, 0xD8, 0x6C, 0x36, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // « left double-angle quote
        0xAC => bitmap(&[
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7E, 0x06, 0x06, 0x06, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ¬ not sign
        0xAD => bitmap(&[
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ­ soft hyphen
        0xAE => bitmap(&[
            0x00, 0x00, 0x3C, 0x42, 0x9D, 0xA5, 0xA5, 0xBD, 0xB9, 0xA5, 0x42, 0x3C, 0x00, 0x00,
            0x00, 0x00,
        ]), // ® registered sign
        0xAF => bitmap(&[
            0x00, 0x7E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ¯ macron
        0xB0 => bitmap(&[
            0x00, 0x00, 0x3C, 0x66, 0x66, 0x3C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ° degree sign
        0xB1 => bitmap(&[
            0x00, 0x00, 0x18, 0x18, 0x7E, 0x18, 0x18, 0x00, 0x7E, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ± plus-minus sign
        0xB2 => bitmap(&[
            0x00, 0x3C, 0x66, 0x0C, 0x18, 0x30, 0x7E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ² superscript two
        0xB3 => bitmap(&[
            0x00, 0x3C, 0x66, 0x0C, 0x06, 0x66, 0x3C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ³ superscript three
        0xB4 => bitmap(&[
            0x00, 0x18, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ´ acute accent
        0xB5 => bitmap(&[
            0x00, 0x00, 0x00, 0x00, 0x00, 0x66, 0x66, 0x66, 0x66, 0x7C, 0x60, 0x60, 0xC0, 0x00,
            0x00, 0x00,
        ]), // µ micro sign
        0xB6 => bitmap(&[
            0x00, 0x7E, 0xD8, 0xD8, 0xD8, 0x78, 0x18, 0x18, 0x18, 0x18, 0x18, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ¶ pilcrow
        0xB7 => bitmap(&[
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x18, 0x18, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // · middle dot
        0xB8 => bitmap(&[
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x18, 0x30,
            0x00, 0x00,
        ]), // ¸ cedilla
        0xB9 => bitmap(&[
            0x00, 0x18, 0x38, 0x18, 0x18, 0x18, 0x7E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ¹ superscript one
        0xBA => bitmap(&[
            0x00, 0x3C, 0x66, 0x66, 0x66, 0x3C, 0x00, 0x7E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // º masculine ordinal
        0xBB => bitmap(&[
            0x00, 0x00, 0x00, 0x00, 0xD8, 0x6C, 0x36, 0x6C, 0xD8, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // » right double-angle quote
        0xBC => bitmap(&[
            0x00, 0x40, 0xC0, 0x40, 0x40, 0x4E, 0xCC, 0x16, 0x36, 0x66, 0xCE, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ¼ one quarter
        0xBD => bitmap(&[
            0x00, 0x40, 0xC0, 0x40, 0x40, 0x4F, 0xC8, 0x18, 0x30, 0x67, 0xCF, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ½ one half
        0xBE => bitmap(&[
            0x00, 0xE0, 0x20, 0xE0, 0x20, 0xEE, 0x6C, 0x16, 0x36, 0x66, 0xCE, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ¾ three quarters
        0xBF => bitmap(&[
            0x00, 0x00, 0x18, 0x18, 0x00, 0x18, 0x18, 0x30, 0x60, 0xC6, 0xC6, 0x7C, 0x00, 0x00,
            0x00, 0x00,
        ]), // ¿ inverted question mark

        // Accented uppercase A variants — base 'A' plus diacritic mark
        // in the top three rows.
        0xC0 => with_diacritic(base_upper_a(), Diacritic::Grave),
        0xC1 => with_diacritic(base_upper_a(), Diacritic::Acute),
        0xC2 => with_diacritic(base_upper_a(), Diacritic::Circumflex),
        0xC3 => with_diacritic(base_upper_a(), Diacritic::Tilde),
        0xC4 => with_diacritic(base_upper_a(), Diacritic::Diaeresis),
        0xC5 => with_diacritic(base_upper_a(), Diacritic::Ring),
        0xC6 => bitmap(&[
            0x00, 0x00, 0x3F, 0x6C, 0xCC, 0xCC, 0xCF, 0xFC, 0xCC, 0xCC, 0xCC, 0xCF, 0x00, 0x00,
            0x00, 0x00,
        ]), // Æ
        0xC7 => with_cedilla(base_upper_c()),
        0xC8 => with_diacritic(base_upper_e(), Diacritic::Grave),
        0xC9 => with_diacritic(base_upper_e(), Diacritic::Acute),
        0xCA => with_diacritic(base_upper_e(), Diacritic::Circumflex),
        0xCB => with_diacritic(base_upper_e(), Diacritic::Diaeresis),
        0xCC => with_diacritic(base_upper_i(), Diacritic::Grave),
        0xCD => with_diacritic(base_upper_i(), Diacritic::Acute),
        0xCE => with_diacritic(base_upper_i(), Diacritic::Circumflex),
        0xCF => with_diacritic(base_upper_i(), Diacritic::Diaeresis),
        0xD0 => bitmap(&[
            0x00, 0x00, 0xF8, 0x6C, 0x66, 0x66, 0xF6, 0x66, 0x66, 0x66, 0x6C, 0xF8, 0x00, 0x00,
            0x00, 0x00,
        ]), // Ð eth
        0xD1 => with_diacritic(base_upper_n(), Diacritic::Tilde),
        0xD2 => with_diacritic(base_upper_o(), Diacritic::Grave),
        0xD3 => with_diacritic(base_upper_o(), Diacritic::Acute),
        0xD4 => with_diacritic(base_upper_o(), Diacritic::Circumflex),
        0xD5 => with_diacritic(base_upper_o(), Diacritic::Tilde),
        0xD6 => with_diacritic(base_upper_o(), Diacritic::Diaeresis),
        0xD7 => bitmap(&[
            0x00, 0x00, 0x00, 0x00, 0x00, 0xC6, 0x6C, 0x38, 0x6C, 0xC6, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // × multiplication sign
        0xD8 => bitmap(&[
            0x00, 0x00, 0x3D, 0x66, 0xCE, 0xCE, 0xD6, 0xE6, 0xE6, 0x66, 0x66, 0xBC, 0x00, 0x00,
            0x00, 0x00,
        ]), // Ø O with stroke
        0xD9 => with_diacritic(base_upper_u(), Diacritic::Grave),
        0xDA => with_diacritic(base_upper_u(), Diacritic::Acute),
        0xDB => with_diacritic(base_upper_u(), Diacritic::Circumflex),
        0xDC => with_diacritic(base_upper_u(), Diacritic::Diaeresis),
        0xDD => with_diacritic(base_upper_y(), Diacritic::Acute),
        0xDE => bitmap(&[
            0x00, 0x00, 0x60, 0x60, 0x7C, 0x66, 0x66, 0x66, 0x66, 0x7C, 0x60, 0x60, 0x00, 0x00,
            0x00, 0x00,
        ]), // Þ thorn
        0xDF => bitmap(&[
            0x00, 0x00, 0x3C, 0x66, 0x66, 0x66, 0x7C, 0x66, 0x66, 0x66, 0x66, 0x7C, 0x60, 0x60,
            0x00, 0x00,
        ]), // ß sharp s

        // Accented lowercase variants — base lowercase letter plus
        // diacritic stamped into the top row(s) above the cap-height
        // (rows 1..=3 of the glyph cell).
        0xE0 => with_diacritic(base_lower_a(), Diacritic::Grave),
        0xE1 => with_diacritic(base_lower_a(), Diacritic::Acute),
        0xE2 => with_diacritic(base_lower_a(), Diacritic::Circumflex),
        0xE3 => with_diacritic(base_lower_a(), Diacritic::Tilde),
        0xE4 => with_diacritic(base_lower_a(), Diacritic::Diaeresis),
        0xE5 => with_diacritic(base_lower_a(), Diacritic::Ring),
        0xE6 => bitmap(&[
            0x00, 0x00, 0x00, 0x00, 0x00, 0x6E, 0x9B, 0x1B, 0x7F, 0xD8, 0xDB, 0x6E, 0x00, 0x00,
            0x00, 0x00,
        ]), // æ
        0xE7 => with_cedilla(base_lower_c()),
        0xE8 => with_diacritic(base_lower_e(), Diacritic::Grave),
        0xE9 => with_diacritic(base_lower_e(), Diacritic::Acute),
        0xEA => with_diacritic(base_lower_e(), Diacritic::Circumflex),
        0xEB => with_diacritic(base_lower_e(), Diacritic::Diaeresis),
        0xEC => with_diacritic(base_lower_i(), Diacritic::Grave),
        0xED => with_diacritic(base_lower_i(), Diacritic::Acute),
        0xEE => with_diacritic(base_lower_i(), Diacritic::Circumflex),
        0xEF => with_diacritic(base_lower_i(), Diacritic::Diaeresis),
        0xF0 => bitmap(&[
            0x00, 0x76, 0xDC, 0x1C, 0x36, 0x3E, 0x66, 0x66, 0x66, 0x66, 0x3C, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ð eth lowercase
        0xF1 => with_diacritic(base_lower_n(), Diacritic::Tilde),
        0xF2 => with_diacritic(base_lower_o(), Diacritic::Grave),
        0xF3 => with_diacritic(base_lower_o(), Diacritic::Acute),
        0xF4 => with_diacritic(base_lower_o(), Diacritic::Circumflex),
        0xF5 => with_diacritic(base_lower_o(), Diacritic::Tilde),
        0xF6 => with_diacritic(base_lower_o(), Diacritic::Diaeresis),
        0xF7 => bitmap(&[
            0x00, 0x00, 0x00, 0x00, 0x18, 0x18, 0x00, 0x7E, 0x00, 0x18, 0x18, 0x00, 0x00, 0x00,
            0x00, 0x00,
        ]), // ÷ division sign
        0xF8 => bitmap(&[
            0x00, 0x00, 0x00, 0x00, 0x02, 0x3C, 0x6E, 0x76, 0x66, 0x76, 0x6E, 0x3C, 0x40, 0x00,
            0x00, 0x00,
        ]), // ø o with stroke
        0xF9 => with_diacritic(base_lower_u(), Diacritic::Grave),
        0xFA => with_diacritic(base_lower_u(), Diacritic::Acute),
        0xFB => with_diacritic(base_lower_u(), Diacritic::Circumflex),
        0xFC => with_diacritic(base_lower_u(), Diacritic::Diaeresis),
        0xFD => with_diacritic(base_lower_y(), Diacritic::Acute),
        0xFE => bitmap(&[
            0x00, 0x00, 0x60, 0x60, 0x7C, 0x66, 0x66, 0x66, 0x66, 0x7C, 0x60, 0x60, 0x00, 0x00,
            0x00, 0x00,
        ]), // þ thorn lowercase
        0xFF => with_diacritic(base_lower_y(), Diacritic::Diaeresis),

        // Defensive fallback — the match is otherwise exhaustive across
        // 0xA1..=0xFF. If we ever miss a codepoint we land here on the
        // fallback dot rather than crashing.
        _ => fallback_dot_bitmap(),
    }
}

/// Diacritic mark applied above a base letter to synthesise an
/// accented Latin-1 glyph.
#[derive(Clone, Copy)]
enum Diacritic {
    Grave,
    Acute,
    Circumflex,
    Tilde,
    Diaeresis,
    Ring,
}

/// Apply a diacritic stamp to the top three rows of a base letter
/// bitmap. The original bitmap's rows shift down by two so the
/// diacritic has space to live in rows 0..=1.
const fn with_diacritic(
    base: [u8; BYTES_PER_GLYPH],
    diacritic: Diacritic,
) -> [u8; BYTES_PER_GLYPH] {
    let mut out = [0u8; BYTES_PER_GLYPH];
    // Shift the base glyph down by two rows so we can paint the
    // diacritic into rows 0..=1.
    let mut i: usize = 2;
    while i < BYTES_PER_GLYPH {
        out[i] = base[i - 2];
        i += 1;
    }
    // Re-introduce a single descender row at the bottom so the
    // diacritic doesn't cost us the bottom margin entirely. (For
    // letters whose original bitmap had inked pixels in row 14/15 the
    // shift drops them, but the visual result remains readable.)
    let (row0, row1) = match diacritic {
        Diacritic::Grave => (0x30u8, 0x18),
        Diacritic::Acute => (0x18u8, 0x30),
        Diacritic::Circumflex => (0x18u8, 0x3C),
        Diacritic::Tilde => (0x36u8, 0x6C),
        Diacritic::Diaeresis => (0x66u8, 0x66),
        Diacritic::Ring => (0x3Cu8, 0x66),
    };
    out[0] = row0;
    out[1] = row1;
    // The shift-down kept the descender ink intact at row 15 already.
    out
}

/// Apply a cedilla underneath a base letter — paints a small hook
/// into rows 13..=14 below the letter's baseline.
const fn with_cedilla(base: [u8; BYTES_PER_GLYPH]) -> [u8; BYTES_PER_GLYPH] {
    let mut out = base;
    out[13] = 0x18;
    out[14] = 0x30;
    out
}

// Base letter bitmaps (copies of the matching ASCII glyphs from
// font_data.rs). Each base is shifted by `with_diacritic` to make
// room for the mark; the shift is necessary because diacritics
// occupy the otherwise-empty rows 0..=1 of the cell, which the
// base letter would normally use for its top stroke.

const fn base_upper_a() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0x10, 0x38, 0x6C, 0xC6, 0xC6, 0xFE, 0xC6, 0xC6, 0xC6, 0xC6, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_upper_c() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0x3C, 0x66, 0xC2, 0xC0, 0xC0, 0xC0, 0xC0, 0xC2, 0x66, 0x3C, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_upper_e() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0xFE, 0x66, 0x62, 0x68, 0x78, 0x68, 0x60, 0x62, 0x66, 0xFE, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_upper_i() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0x3C, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x3C, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_upper_n() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0xC6, 0xE6, 0xF6, 0xFE, 0xDE, 0xCE, 0xC6, 0xC6, 0xC6, 0xC6, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_upper_o() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0x38, 0x6C, 0xC6, 0xC6, 0xC6, 0xC6, 0xC6, 0xC6, 0x6C, 0x38, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_upper_u() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0xC6, 0xC6, 0xC6, 0xC6, 0xC6, 0xC6, 0xC6, 0xC6, 0x6C, 0x38, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_upper_y() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0xC6, 0xC6, 0xC6, 0xC6, 0x6C, 0x38, 0x18, 0x18, 0x18, 0x3C, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_lower_a() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0x00, 0x00, 0x00, 0x78, 0x0C, 0x7C, 0xCC, 0xCC, 0xCC, 0x76, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_lower_c() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0x00, 0x00, 0x00, 0x7C, 0xC6, 0xC0, 0xC0, 0xC0, 0xC6, 0x7C, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_lower_e() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0x00, 0x00, 0x00, 0x7C, 0xC6, 0xFE, 0xC0, 0xC0, 0xC6, 0x7C, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_lower_i() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0x18, 0x18, 0x00, 0x38, 0x18, 0x18, 0x18, 0x18, 0x18, 0x3C, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_lower_n() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0x00, 0x00, 0x00, 0xDC, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_lower_o() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0x00, 0x00, 0x00, 0x7C, 0xC6, 0xC6, 0xC6, 0xC6, 0xC6, 0x7C, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_lower_u() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0x00, 0x00, 0x00, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0x76, 0x00, 0x00, 0x00,
        0x00,
    ]
}

const fn base_lower_y() -> [u8; BYTES_PER_GLYPH] {
    [
        0x00, 0x00, 0x00, 0x00, 0x00, 0xC6, 0xC6, 0xC6, 0xC6, 0xC6, 0x7E, 0x06, 0x0C, 0xF8, 0x00,
        0x00,
    ]
}

/// Compile-time helper: build a 16-byte bitmap from a 16-byte slice.
const fn bitmap(b: &[u8; BYTES_PER_GLYPH]) -> [u8; BYTES_PER_GLYPH] {
    *b
}

// ---------------------------------------------------------------------------
// Box-drawing bitmaps
// ---------------------------------------------------------------------------

/// One side of a box-drawing character. Each side is one of these
/// kinds; `EdgeKind::None` means no stroke.
#[derive(Clone, Copy, PartialEq, Eq)]
enum EdgeKind {
    None,
    Light,
    Heavy,
    Double,
}

/// `(north, east, south, west)` edge spec for a single box-drawing
/// codepoint. Edges are painted from the cell's centre to the
/// matching side; the rendering function picks pixel patterns for
/// each edge kind.
type EdgeSpec = [EdgeKind; 4];

/// Cell centre row (8) and column (3, the centre of an 8-pixel-wide
/// cell — bit 4 of the mask, i.e. the 4th pixel from the left).
const CENTER_ROW: usize = 8;
const CENTER_COL_BIT: u8 = 0x10; // pixel mask for column 3

/// Pixel-column masks for the centre stroke and an immediately
/// adjacent stroke (used for double / heavy variants).
const MASK_CENTER: u8 = 0x18; // columns 3+4 — heavy thick stroke
const MASK_DOUBLE_RAILS: u8 = 0x14; // columns 3 and 5 — outer rails of a double line

/// Per-codepoint edge specs for codepoints that fit the four-edge
/// model (U+250C..=U+2570 most variants). Codepoints handled by
/// special cases (arcs, diagonals, half-line endpoints) return `None`
/// from this function so the renderer routes them through the
/// case-specific path.
const fn edge_spec_for(codepoint: u32) -> Option<EdgeSpec> {
    use EdgeKind::*;
    match codepoint {
        // Plain horizontals / verticals.
        0x2500 => Some([None, Light, None, Light]),
        0x2501 => Some([None, Heavy, None, Heavy]),
        0x2502 => Some([Light, None, Light, None]),
        0x2503 => Some([Heavy, None, Heavy, None]),

        // Dashed approximations: render as plain light lines (visual
        // fidelity is sacrificed for code size; real terminals
        // commonly fall back this way too).
        0x2504..=0x2507 => Some([None, Light, None, Light]),
        0x2508..=0x250B => Some([Light, None, Light, None]),

        // Corners — top-left family.
        0x250C => Some([None, Light, Light, None]),
        0x250D => Some([None, Heavy, Light, None]),
        0x250E => Some([None, Light, Heavy, None]),
        0x250F => Some([None, Heavy, Heavy, None]),

        // Corners — top-right family.
        0x2510 => Some([None, None, Light, Light]),
        0x2511 => Some([None, None, Light, Heavy]),
        0x2512 => Some([None, None, Heavy, Light]),
        0x2513 => Some([None, None, Heavy, Heavy]),

        // Corners — bottom-left family.
        0x2514 => Some([Light, Light, None, None]),
        0x2515 => Some([Light, Heavy, None, None]),
        0x2516 => Some([Heavy, Light, None, None]),
        0x2517 => Some([Heavy, Heavy, None, None]),

        // Corners — bottom-right family.
        0x2518 => Some([Light, None, None, Light]),
        0x2519 => Some([Light, None, None, Heavy]),
        0x251A => Some([Heavy, None, None, Light]),
        0x251B => Some([Heavy, None, None, Heavy]),

        // T-junctions: vertical on the left.
        0x251C => Some([Light, Light, Light, None]),
        0x251D => Some([Light, Heavy, Light, None]),
        0x251E => Some([Heavy, Light, Light, None]),
        0x251F => Some([Light, Light, Heavy, None]),
        0x2520 => Some([Heavy, Light, Heavy, None]),
        0x2521 => Some([Heavy, Heavy, Light, None]),
        0x2522 => Some([Light, Heavy, Heavy, None]),
        0x2523 => Some([Heavy, Heavy, Heavy, None]),

        // T-junctions: vertical on the right.
        0x2524 => Some([Light, None, Light, Light]),
        0x2525 => Some([Light, None, Light, Heavy]),
        0x2526 => Some([Heavy, None, Light, Light]),
        0x2527 => Some([Light, None, Heavy, Light]),
        0x2528 => Some([Heavy, None, Heavy, Light]),
        0x2529 => Some([Heavy, None, Light, Heavy]),
        0x252A => Some([Light, None, Heavy, Heavy]),
        0x252B => Some([Heavy, None, Heavy, Heavy]),

        // T-junctions: horizontal on top.
        0x252C => Some([None, Light, Light, Light]),
        0x252D => Some([None, Light, Light, Heavy]),
        0x252E => Some([None, Heavy, Light, Light]),
        0x252F => Some([None, Heavy, Light, Heavy]),
        0x2530 => Some([None, Light, Heavy, Light]),
        0x2531 => Some([None, Light, Heavy, Heavy]),
        0x2532 => Some([None, Heavy, Heavy, Light]),
        0x2533 => Some([None, Heavy, Heavy, Heavy]),

        // T-junctions: horizontal on bottom.
        0x2534 => Some([Light, Light, None, Light]),
        0x2535 => Some([Light, Light, None, Heavy]),
        0x2536 => Some([Light, Heavy, None, Light]),
        0x2537 => Some([Light, Heavy, None, Heavy]),
        0x2538 => Some([Heavy, Light, None, Light]),
        0x2539 => Some([Heavy, Light, None, Heavy]),
        0x253A => Some([Heavy, Heavy, None, Light]),
        0x253B => Some([Heavy, Heavy, None, Heavy]),

        // 4-way crosses.
        0x253C => Some([Light, Light, Light, Light]),
        0x253D => Some([Light, Light, Light, Heavy]),
        0x253E => Some([Light, Heavy, Light, Light]),
        0x253F => Some([Light, Heavy, Light, Heavy]),
        0x2540 => Some([Heavy, Light, Light, Light]),
        0x2541 => Some([Light, Light, Heavy, Light]),
        0x2542 => Some([Heavy, Light, Heavy, Light]),
        0x2543 => Some([Heavy, Light, Light, Heavy]),
        0x2544 => Some([Heavy, Heavy, Light, Light]),
        0x2545 => Some([Light, Light, Heavy, Heavy]),
        0x2546 => Some([Light, Heavy, Heavy, Light]),
        0x2547 => Some([Heavy, Heavy, Light, Heavy]),
        0x2548 => Some([Light, Heavy, Heavy, Heavy]),
        0x2549 => Some([Heavy, Light, Heavy, Heavy]),
        0x254A => Some([Heavy, Heavy, Heavy, Light]),
        0x254B => Some([Heavy, Heavy, Heavy, Heavy]),

        // Double-line horizontals / verticals.
        0x2550 => Some([None, Double, None, Double]),
        0x2551 => Some([Double, None, Double, None]),

        // Mixed single/double corners and T-junctions (0x2552..=0x256B).
        // Treat each pair as the "matching" double-side variant.
        0x2552 => Some([None, Double, Light, None]),
        0x2553 => Some([None, Light, Double, None]),
        0x2554 => Some([None, Double, Double, None]),
        0x2555 => Some([None, None, Light, Double]),
        0x2556 => Some([None, None, Double, Light]),
        0x2557 => Some([None, None, Double, Double]),
        0x2558 => Some([Light, Double, None, None]),
        0x2559 => Some([Double, Light, None, None]),
        0x255A => Some([Double, Double, None, None]),
        0x255B => Some([Light, None, None, Double]),
        0x255C => Some([Double, None, None, Light]),
        0x255D => Some([Double, None, None, Double]),
        0x255E => Some([Light, Double, Light, None]),
        0x255F => Some([Double, Light, Double, None]),
        0x2560 => Some([Double, Double, Double, None]),
        0x2561 => Some([Light, None, Light, Double]),
        0x2562 => Some([Double, None, Double, Light]),
        0x2563 => Some([Double, None, Double, Double]),
        0x2564 => Some([None, Double, Light, Double]),
        0x2565 => Some([None, Light, Double, Light]),
        0x2566 => Some([None, Double, Double, Double]),
        0x2567 => Some([Light, Double, None, Double]),
        0x2568 => Some([Double, Light, None, Light]),
        0x2569 => Some([Double, Double, None, Double]),
        0x256A => Some([Light, Double, Light, Double]),
        0x256B => Some([Double, Light, Double, Light]),
        0x256C => Some([Double, Double, Double, Double]),

        _ => Option::None,
    }
}

/// Render an `EdgeSpec` to a 16-byte 8×16 bitmap.
const fn render_edge_spec(spec: EdgeSpec) -> [u8; BYTES_PER_GLYPH] {
    let mut out = [0u8; BYTES_PER_GLYPH];
    let north = spec[0];
    let east = spec[1];
    let south = spec[2];
    let west = spec[3];

    // North stroke — column at centre, rows 0..CENTER_ROW.
    let mut r: usize = 0;
    while r < CENTER_ROW {
        out[r] |= column_mask(north);
        r += 1;
    }
    // South stroke — rows CENTER_ROW..BYTES_PER_GLYPH.
    let mut r: usize = CENTER_ROW;
    while r < BYTES_PER_GLYPH {
        out[r] |= column_mask(south);
        r += 1;
    }
    // East / West strokes — rows in a horizontal band around centre.
    // Double-line horizontals use rows 6/7 + 8/9.
    let west_mask_high = row_mask_left(west, true);
    let west_mask_low = row_mask_left(west, false);
    let east_mask_high = row_mask_right(east, true);
    let east_mask_low = row_mask_right(east, false);

    out[CENTER_ROW - 1] |= west_mask_high | east_mask_high;
    out[CENTER_ROW] |= west_mask_low | east_mask_low;

    // For "Double" strokes, paint a second parallel line two rows
    // away so the result reads as a double line.
    if matches!(north, EdgeKind::Double) {
        // North-bound double rail: paint another column 2 pixels away.
        let mut r: usize = 0;
        while r < CENTER_ROW {
            out[r] |= double_north_extra();
            r += 1;
        }
    }
    if matches!(south, EdgeKind::Double) {
        let mut r: usize = CENTER_ROW;
        while r < BYTES_PER_GLYPH {
            out[r] |= double_south_extra();
            r += 1;
        }
    }
    if matches!(east, EdgeKind::Double) {
        out[CENTER_ROW - 2] |= east_double_extra();
        out[CENTER_ROW + 1] |= east_double_extra();
    }
    if matches!(west, EdgeKind::Double) {
        out[CENTER_ROW - 2] |= west_double_extra();
        out[CENTER_ROW + 1] |= west_double_extra();
    }

    out
}

const fn column_mask(kind: EdgeKind) -> u8 {
    match kind {
        EdgeKind::None => 0,
        EdgeKind::Light => CENTER_COL_BIT,
        EdgeKind::Heavy => MASK_CENTER,
        EdgeKind::Double => MASK_DOUBLE_RAILS,
    }
}

const fn row_mask_left(kind: EdgeKind, _high_row: bool) -> u8 {
    match kind {
        EdgeKind::None => 0,
        EdgeKind::Light | EdgeKind::Double => 0xF0, // four leftmost pixels
        EdgeKind::Heavy => 0xF0,
    }
}

const fn row_mask_right(kind: EdgeKind, _high_row: bool) -> u8 {
    match kind {
        EdgeKind::None => 0,
        EdgeKind::Light | EdgeKind::Double => 0x1F, // five rightmost pixels
        EdgeKind::Heavy => 0x1F,
    }
}

const fn double_north_extra() -> u8 {
    // Second rail at column 5.
    0x04
}

const fn double_south_extra() -> u8 {
    0x04
}

const fn east_double_extra() -> u8 {
    0x1F
}

const fn west_double_extra() -> u8 {
    0xF0
}

/// Special-case box-drawing codepoints not covered by `edge_spec_for`.
const fn special_box_bitmap_for(codepoint: u32) -> [u8; BYTES_PER_GLYPH] {
    match codepoint {
        // Light arc corners: visually close to the matching right-
        // angle corner. Approximated as the right-angle corner.
        0x256D => render_edge_spec([
            EdgeKind::None,
            EdgeKind::Light,
            EdgeKind::Light,
            EdgeKind::None,
        ]),
        0x256E => render_edge_spec([
            EdgeKind::None,
            EdgeKind::None,
            EdgeKind::Light,
            EdgeKind::Light,
        ]),
        0x256F => render_edge_spec([
            EdgeKind::Light,
            EdgeKind::None,
            EdgeKind::None,
            EdgeKind::Light,
        ]),
        0x2570 => render_edge_spec([
            EdgeKind::Light,
            EdgeKind::Light,
            EdgeKind::None,
            EdgeKind::None,
        ]),

        // Diagonals.
        0x2571 => [
            // Forward slash from bottom-left to top-right (/)
            0x01, 0x03, 0x02, 0x06, 0x04, 0x0C, 0x08, 0x18, 0x10, 0x30, 0x20, 0x60, 0x40, 0xC0,
            0x80, 0x00,
        ],
        0x2572 => [
            // Back slash from top-left to bottom-right (\)
            0x80, 0xC0, 0x40, 0x60, 0x20, 0x30, 0x10, 0x18, 0x08, 0x0C, 0x04, 0x06, 0x02, 0x03,
            0x01, 0x00,
        ],
        0x2573 => [
            // Cross: both diagonals OR'd together.
            0x81, 0xC3, 0x42, 0x66, 0x24, 0x3C, 0x18, 0x18, 0x18, 0x3C, 0x24, 0x66, 0x42, 0xC3,
            0x81, 0x00,
        ],

        // Half-line endpoints (U+2574..U+257B).
        0x2574 => half_left(EdgeKind::Light),
        0x2575 => half_top(EdgeKind::Light),
        0x2576 => half_right(EdgeKind::Light),
        0x2577 => half_bottom(EdgeKind::Light),
        0x2578 => half_left(EdgeKind::Heavy),
        0x2579 => half_top(EdgeKind::Heavy),
        0x257A => half_right(EdgeKind::Heavy),
        0x257B => half_bottom(EdgeKind::Heavy),

        // Mixed half-strokes: U+257C..U+257F join one light edge to a
        // heavy edge through the centre. We render each as the
        // matching full horizontal/vertical and accept the
        // visual approximation.
        0x257C => render_edge_spec([
            EdgeKind::None,
            EdgeKind::Heavy,
            EdgeKind::None,
            EdgeKind::Light,
        ]),
        0x257D => render_edge_spec([
            EdgeKind::Light,
            EdgeKind::None,
            EdgeKind::Heavy,
            EdgeKind::None,
        ]),
        0x257E => render_edge_spec([
            EdgeKind::None,
            EdgeKind::Light,
            EdgeKind::None,
            EdgeKind::Heavy,
        ]),
        0x257F => render_edge_spec([
            EdgeKind::Heavy,
            EdgeKind::None,
            EdgeKind::Light,
            EdgeKind::None,
        ]),

        _ => fallback_dot_bitmap(),
    }
}

const fn half_left(kind: EdgeKind) -> [u8; BYTES_PER_GLYPH] {
    let mut out = [0u8; BYTES_PER_GLYPH];
    let mask = row_mask_left(kind, true);
    out[CENTER_ROW - 1] |= mask;
    out[CENTER_ROW] |= mask;
    out
}

const fn half_right(kind: EdgeKind) -> [u8; BYTES_PER_GLYPH] {
    let mut out = [0u8; BYTES_PER_GLYPH];
    let mask = row_mask_right(kind, true);
    out[CENTER_ROW - 1] |= mask;
    out[CENTER_ROW] |= mask;
    out
}

const fn half_top(kind: EdgeKind) -> [u8; BYTES_PER_GLYPH] {
    let mut out = [0u8; BYTES_PER_GLYPH];
    let mask = column_mask(kind);
    let mut r: usize = 0;
    while r < CENTER_ROW {
        out[r] |= mask;
        r += 1;
    }
    out
}

const fn half_bottom(kind: EdgeKind) -> [u8; BYTES_PER_GLYPH] {
    let mut out = [0u8; BYTES_PER_GLYPH];
    let mask = column_mask(kind);
    let mut r: usize = CENTER_ROW;
    while r < BYTES_PER_GLYPH {
        out[r] |= mask;
        r += 1;
    }
    out
}

const fn build_box_drawing_bitmaps() -> [[u8; BYTES_PER_GLYPH]; BOX_DRAWING_COUNT] {
    let mut out = [[0u8; BYTES_PER_GLYPH]; BOX_DRAWING_COUNT];
    let mut i: usize = 0;
    while i < BOX_DRAWING_COUNT {
        let codepoint = BOX_DRAWING_FIRST + i as u32;
        let bm = match edge_spec_for(codepoint) {
            Option::Some(spec) => render_edge_spec(spec),
            Option::None => special_box_bitmap_for(codepoint),
        };
        out[i] = bm;
        i += 1;
    }
    out
}

// ---------------------------------------------------------------------------
// Fallback dot
// ---------------------------------------------------------------------------

const fn fallback_dot_bitmap() -> [u8; BYTES_PER_GLYPH] {
    let mut out = [0u8; BYTES_PER_GLYPH];
    // A 2×2 block at the cell's centre.
    out[7] = 0x18;
    out[8] = 0x18;
    out
}

// ---------------------------------------------------------------------------
// Static tables and the public resolver
// ---------------------------------------------------------------------------

/// Bitmap storage for the Latin-1 supplement table.
static LATIN1_BITMAPS: [[u8; BYTES_PER_GLYPH]; LATIN1_COUNT] = build_latin1_bitmaps();

/// Bitmap storage for the Unicode box-drawing table.
static BOX_DRAWING_BITMAPS: [[u8; BYTES_PER_GLYPH]; BOX_DRAWING_COUNT] =
    build_box_drawing_bitmaps();

/// Bitmap storage for the centred-dot fallback.
static FALLBACK_DOT_BITMAP: [u8; BYTES_PER_GLYPH] = fallback_dot_bitmap();

/// Latin-1 supplement [`Glyph`] table — `GLYPH_TABLE_LATIN1[i]` covers
/// codepoint `LATIN1_FIRST + i`.
///
/// Phase 69b Track C — 128 entries covering U+0080..=U+00FF. C1
/// control characters and NBSP render as blank cells; all other
/// codepoints render a visible glyph.
pub static GLYPH_TABLE_LATIN1: [Glyph; LATIN1_COUNT] = build_latin1_glyph_table();

/// Unicode box-drawing block [`Glyph`] table —
/// `GLYPH_TABLE_BOX_DRAWING[i]` covers codepoint
/// `BOX_DRAWING_FIRST + i`.
///
/// Phase 69b Track D — 128 entries covering U+2500..=U+257F.
pub static GLYPH_TABLE_BOX_DRAWING: [Glyph; BOX_DRAWING_COUNT] = build_box_drawing_glyph_table();

/// Centred-dot fallback glyph, used whenever
/// [`resolve_glyph`] is called with a codepoint outside the covered
/// ranges (and outside the control-character ranges, which render
/// blank).
///
/// Phase 69b Track E — single fallback for every "we don't have a
/// glyph yet" case. Renderers can compare a returned `&Glyph` against
/// this value to special-case the visible-placeholder behaviour.
pub static FALLBACK_DOT_GLYPH: Glyph = Glyph {
    width: CELL_WIDTH,
    height: CELL_HEIGHT,
    bitmap: &FALLBACK_DOT_BITMAP,
};

/// Blank glyph used for control characters (U+0000..=U+001F,
/// U+0080..=U+009F, U+007F) — keeps a typed value the renderer can
/// hand back when the caller asks for a control codepoint.
pub static BLANK_GLYPH: Glyph = Glyph {
    width: CELL_WIDTH,
    height: CELL_HEIGHT,
    bitmap: &BLANK,
};

const fn build_latin1_glyph_table() -> [Glyph; LATIN1_COUNT] {
    let mut out: [Glyph; LATIN1_COUNT] = [Glyph {
        width: CELL_WIDTH,
        height: CELL_HEIGHT,
        bitmap: &BLANK,
    }; LATIN1_COUNT];
    let mut i: usize = 0;
    while i < LATIN1_COUNT {
        out[i] = Glyph {
            width: CELL_WIDTH,
            height: CELL_HEIGHT,
            // Reference into the static `LATIN1_BITMAPS` slot. Each
            // sub-array is itself a `'static` slice because the
            // owning array is `static`.
            bitmap: latin1_bitmap_slice(i),
        };
        i += 1;
    }
    out
}

const fn latin1_bitmap_slice(index: usize) -> &'static [u8] {
    // Build a static reference into the bitmaps array by treating
    // each row as a slice. The const-context restriction that
    // forbids index-into-array via `&LATIN1_BITMAPS[i]` is satisfied
    // by `&LATIN1_BITMAPS[i][..]` — both forms are accepted at
    // compile time for `static` arrays of `Copy` types.
    let slot: &[u8; BYTES_PER_GLYPH] = &LATIN1_BITMAPS[index];
    slot
}

const fn build_box_drawing_glyph_table() -> [Glyph; BOX_DRAWING_COUNT] {
    let mut out: [Glyph; BOX_DRAWING_COUNT] = [Glyph {
        width: CELL_WIDTH,
        height: CELL_HEIGHT,
        bitmap: &BLANK,
    }; BOX_DRAWING_COUNT];
    let mut i: usize = 0;
    while i < BOX_DRAWING_COUNT {
        out[i] = Glyph {
            width: CELL_WIDTH,
            height: CELL_HEIGHT,
            bitmap: box_drawing_bitmap_slice(i),
        };
        i += 1;
    }
    out
}

const fn box_drawing_bitmap_slice(index: usize) -> &'static [u8] {
    let slot: &[u8; BYTES_PER_GLYPH] = &BOX_DRAWING_BITMAPS[index];
    slot
}

/// Phase 69b Track E — single glyph resolver.
///
/// Dispatches by codepoint:
///
/// - **U+0020..=U+007E** → ASCII bitmap table
///   ([`crate::session::font_data::GLYPH_BITMAPS`]).
/// - **U+0080..=U+00FF** → [`GLYPH_TABLE_LATIN1`].
/// - **U+2500..=U+257F** → [`GLYPH_TABLE_BOX_DRAWING`].
/// - **U+0000..=U+001F**, **U+007F**, **U+0080..=U+009F** →
///   [`BLANK_GLYPH`] (control characters render to a blank cell;
///   `0x7F` DEL is covered by the ASCII table already but kept here
///   for symmetry).
/// - Everything else → [`FALLBACK_DOT_GLYPH`].
///
/// The returned reference always has a `'static` lifetime so renderers
/// can hold onto it for the duration of a paint pass without copying.
pub fn resolve_glyph(codepoint: u32) -> &'static Glyph {
    // Control characters render blank — same behaviour every terminal
    // applies to invisible control bytes.
    if codepoint <= 0x1F
        || codepoint == 0x7F
        || (0x80..=0x9F).contains(&codepoint)
        || codepoint == 0xA0
    {
        return &BLANK_GLYPH;
    }
    if (ASCII_FIRST..=ASCII_LAST).contains(&codepoint) {
        let idx = (codepoint - ASCII_FIRST) as usize;
        return &GLYPH_BITMAPS[idx];
    }
    if (LATIN1_FIRST..=LATIN1_LAST).contains(&codepoint) {
        let idx = (codepoint - LATIN1_FIRST) as usize;
        return &GLYPH_TABLE_LATIN1[idx];
    }
    if (BOX_DRAWING_FIRST..=BOX_DRAWING_LAST).contains(&codepoint) {
        let idx = (codepoint - BOX_DRAWING_FIRST) as usize;
        return &GLYPH_TABLE_BOX_DRAWING[idx];
    }
    &FALLBACK_DOT_GLYPH
}

// ---------------------------------------------------------------------------
// East Asian Width
// ---------------------------------------------------------------------------

/// Phase 69b Track F — East Asian Width accounting.
///
/// Returns `2` for codepoints in the canonical always-wide CJK /
/// halfwidth-fullwidth ranges, and `1` for everything else. Glyph
/// tables for these ranges are not present in Phase 69b (they remain
/// deferred); landing the accounting here keeps the cell grid honest
/// so future phases that ship the tables only need to extend the
/// resolver, not the screen state machine.
///
/// Returned widths:
///
/// - **U+2E80..=U+9FFF** — CJK Radicals through CJK Unified
///   Ideographs.
/// - **U+3000..=U+30FF** — CJK Symbols and Punctuation through
///   Katakana.
/// - **U+AC00..=U+D7AF** — Hangul Syllables.
/// - **U+F900..=U+FAFF** — CJK Compatibility Ideographs.
/// - **U+FE30..=U+FE4F** — CJK Compatibility Forms.
/// - **U+FF00..=U+FF60** — Halfwidth and Fullwidth Forms (fullwidth
///   half).
/// - **U+FFE0..=U+FFE6** — Fullwidth signs.
pub fn width_of(codepoint: u32) -> u8 {
    if (0x2E80..=0x9FFF).contains(&codepoint)
        || (0x3000..=0x30FF).contains(&codepoint)
        || (0xAC00..=0xD7AF).contains(&codepoint)
        || (0xF900..=0xFAFF).contains(&codepoint)
        || (0xFE30..=0xFE4F).contains(&codepoint)
        || (0xFF00..=0xFF60).contains(&codepoint)
        || (0xFFE0..=0xFFE6).contains(&codepoint)
    {
        2
    } else {
        1
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Phase 69b Track C — table has exactly 128 entries covering
    /// the Latin-1 supplement range.
    #[test]
    fn latin1_table_size_matches_block() {
        assert_eq!(GLYPH_TABLE_LATIN1.len(), 128);
        assert_eq!(LATIN1_LAST - LATIN1_FIRST + 1, 128);
    }

    /// Phase 69b Track C — C1 control range (U+0080..=U+009F) and
    /// NBSP (U+00A0) render as a blank cell.
    #[test]
    fn latin1_c1_control_range_is_blank() {
        for cp in 0x80u32..=0xA0 {
            let g = resolve_glyph(cp);
            assert!(
                g.bitmap.iter().all(|&b| b == 0),
                "codepoint {:#06x} must render blank",
                cp
            );
        }
    }

    /// Phase 69b Track C — representative accented letters return a
    /// non-blank bitmap.
    #[test]
    fn latin1_representative_letters_have_inked_pixels() {
        for &cp in &[0x00C7, 0x00DC, 0x00E9, 0x00F1, 0x00A9, 0x00B1] {
            let g = resolve_glyph(cp);
            assert!(
                g.bitmap.iter().any(|&b| b != 0),
                "codepoint {:#06x} must have inked pixels",
                cp
            );
        }
    }

    /// Phase 69b Track C — a representative subset's pixels match
    /// the expected base-letter + diacritic pattern. Specifically
    /// 'é' (U+00E9) must have a diacritic stamp in rows 0..=1 and
    /// the lower-case 'e' shape in the shifted-down body.
    #[test]
    fn latin1_e_acute_bitmap_has_diacritic_then_base() {
        let g = resolve_glyph(0x00E9);
        // Diacritic stamp is row 0 = 0x18, row 1 = 0x30 per the
        // Acute mapping in `with_diacritic`.
        assert_eq!(g.bitmap[0], 0x18, "acute mark row 0");
        assert_eq!(g.bitmap[1], 0x30, "acute mark row 1");
        // The base lowercase 'e' shifted down by 2 means base[5] is
        // at out[7]: base_lower_e()[5] == 0x7C.
        assert_eq!(g.bitmap[7], 0x7C, "shifted-down 'e' top edge");
    }

    /// Phase 69b Track D — table has exactly 128 entries covering
    /// the Unicode box-drawing block.
    #[test]
    fn box_drawing_table_size_matches_block() {
        assert_eq!(GLYPH_TABLE_BOX_DRAWING.len(), 128);
        assert_eq!(BOX_DRAWING_LAST - BOX_DRAWING_FIRST + 1, 128);
    }

    /// Phase 69b Track D — the four light corners have a stroke
    /// going to the right cell side and a stroke going down/up the
    /// cell.
    #[test]
    fn box_drawing_corners_have_two_strokes_each() {
        // U+250C ┌ — light down + light right.
        let g = resolve_glyph(0x250C);
        // Centre row (row 7, 0-indexed) carries the east stroke.
        assert!(
            g.bitmap[7] & 0x1F != 0,
            "east stroke missing for U+250C: {:02x}",
            g.bitmap[7]
        );
        // South stroke runs from centre row to bottom.
        let south_pixels: u32 = g.bitmap[CENTER_ROW..].iter().map(|b| *b as u32).sum();
        assert!(south_pixels > 0, "south stroke missing for U+250C");

        // U+2510 ┐ — west + south.
        let g = resolve_glyph(0x2510);
        assert!(g.bitmap[7] & 0xF0 != 0, "west stroke missing for U+2510");

        // U+2514 └ — north + east.
        let g = resolve_glyph(0x2514);
        let north_pixels: u32 = g.bitmap[..CENTER_ROW].iter().map(|b| *b as u32).sum();
        assert!(north_pixels > 0, "north stroke missing for U+2514");

        // U+2518 ┘ — north + west.
        let g = resolve_glyph(0x2518);
        let north_pixels: u32 = g.bitmap[..CENTER_ROW].iter().map(|b| *b as u32).sum();
        assert!(north_pixels > 0, "north stroke missing for U+2518");
    }

    /// Phase 69b Track D — the four T-junctions carry three strokes
    /// each.
    #[test]
    fn box_drawing_t_junctions_have_three_strokes() {
        // U+252C ┬ — east + south + west.
        let g = resolve_glyph(0x252C);
        assert!(g.bitmap[7] & 0x1F != 0, "east stroke missing for U+252C");
        assert!(g.bitmap[7] & 0xF0 != 0, "west stroke missing for U+252C");
        let south_pixels: u32 = g.bitmap[CENTER_ROW..].iter().map(|b| *b as u32).sum();
        assert!(south_pixels > 0, "south stroke missing for U+252C");
    }

    /// Phase 69b Track D — the plain horizontal U+2500 has a stroke
    /// across the centre row with no vertical ink.
    #[test]
    fn box_drawing_horizontal_is_just_centre_band() {
        let g = resolve_glyph(0x2500);
        // Centre row + adjacent row carry ink.
        assert!(g.bitmap[7] != 0 || g.bitmap[8] != 0);
        // Top and bottom thirds carry no ink.
        for r in 0..6 {
            assert_eq!(g.bitmap[r], 0, "row {r} must be blank for U+2500");
        }
        for r in 10..BYTES_PER_GLYPH {
            assert_eq!(g.bitmap[r], 0, "row {r} must be blank for U+2500");
        }
    }

    /// Phase 69b Track E — every range boundary returns the expected
    /// glyph type.
    #[test]
    fn resolver_dispatches_each_range_to_its_table() {
        // Below the printable ASCII range — control char → blank.
        assert!(resolve_glyph(0x00).bitmap.iter().all(|&b| b == 0));
        // ASCII boundary low.
        assert!(resolve_glyph(0x20).bitmap.iter().any(|&b| b == 0));
        // ASCII boundary high.
        assert!(core::ptr::eq(
            resolve_glyph(0x41).bitmap.as_ptr(),
            GLYPH_BITMAPS[(0x41 - ASCII_FIRST) as usize].bitmap.as_ptr()
        ));
        // Latin-1 boundary.
        let g = resolve_glyph(0xA1);
        let expected = &GLYPH_TABLE_LATIN1[0x21];
        assert!(core::ptr::eq(g.bitmap.as_ptr(), expected.bitmap.as_ptr()));
        // Box-drawing boundary.
        let g = resolve_glyph(0x2500);
        let expected = &GLYPH_TABLE_BOX_DRAWING[0];
        assert!(core::ptr::eq(g.bitmap.as_ptr(), expected.bitmap.as_ptr()));
        // CJK codepoint → fallback dot (no glyph table for CJK in
        // Phase 69b).
        let g = resolve_glyph(0x4E2D);
        assert!(core::ptr::eq(
            g.bitmap.as_ptr(),
            FALLBACK_DOT_GLYPH.bitmap.as_ptr()
        ));
    }

    /// Phase 69b Track F — every range boundary returns width 2.
    #[test]
    fn width_of_canonical_cjk_ranges_returns_two() {
        let two = &[
            0x2E80u32, 0x9FFF, 0x3000, 0x30FF, 0xAC00, 0xD7AF, 0xF900, 0xFAFF, 0xFE30, 0xFE4F,
            0xFF00, 0xFF60, 0xFFE0, 0xFFE6,
        ];
        for &cp in two {
            assert_eq!(width_of(cp), 2, "codepoint {:#06x} must be width 2", cp);
        }
    }

    /// Phase 69b Track F — codepoints outside the canonical wide
    /// ranges return width 1.
    #[test]
    fn width_of_non_cjk_returns_one() {
        let one = &[
            0x0041u32, 0x00E9, 0x2500, 0x2E7F, // one below the CJK Radicals start
            0xA000, // one above Hangul Syllables end
            0xFB00, // boundary above CJK Compatibility Forms
        ];
        for &cp in one {
            assert_eq!(width_of(cp), 1, "codepoint {:#06x} must be width 1", cp);
        }
    }

    /// Phase 69b Track E — the fallback dot has exactly four inked
    /// pixels (a 2×2 block at the cell centre) — sanity-check the
    /// shape stays small.
    #[test]
    fn fallback_dot_is_a_two_by_two_block() {
        assert_eq!(FALLBACK_DOT_GLYPH.bitmap[7], 0x18);
        assert_eq!(FALLBACK_DOT_GLYPH.bitmap[8], 0x18);
        // All other rows are blank.
        for (r, &b) in FALLBACK_DOT_GLYPH.bitmap.iter().enumerate() {
            if r != 7 && r != 8 {
                assert_eq!(b, 0, "row {r} of fallback dot must be blank");
            }
        }
    }
}
